class_name Standing

# M48 -- Standings & flags (IFF v2). Static rules module: pure functions plus
# two small shared registries. No Node state -- everything per-observer lives
# on the observer ship's own contact records (contact["standing"]/
# ["standing_reason"]/["aggro_hits"], see ship.gd).
#
# Standing is FOUR tiers -- FRIENDLY / NEUTRAL / UNREPORTED / HOSTILE -- the
# dispositions that mean the SAME thing to every observer holding them, so
# they can ride the datalink and paint the contacts panel. "Suspicious" is
# deliberately NOT a standing: it has no shared meaning (a patrol's "acting
# like a predator" vs a pirate's "prey that might be a trap"), so it lives in
# each AI's own role-specific assessment (behavior-tree blackboard), never on
# the shared contact record. See design_ideas/economy_and_piracy.md.
#
# Reference this via the preload-const convention (see CLAUDE.md -- the
# git-tracked global class cache isn't regenerated by the headless --run-test
# path, so relying on the bare `Standing` global class name can fail to
# resolve until someone reopens the editor):
#   const Standing = preload("res://scripts/combat/standing.gd")
#
# See implementation_plans/m48_standings_flags_design.md (the file-pinned
# spec) and design_ideas/economy_and_piracy.md (the standing table + the
# three angle rules: assistance exemption, authority flags, attribution
# confidence gate) for the rule rationale this module implements.

const FRIENDLY := "FRIENDLY"
const NEUTRAL := "NEUTRAL"
const UNREPORTED := "UNREPORTED"
const HOSTILE := "HOSTILE"

const FLAG_PIRATE := "JOLLY_ROGER"
const FLAG_DRIFT := "SOVEREIGN_DRIFT"     # home faction / militia
const FLAG_CIVILIAN := "DRIFT_CIVILIAN"   # mobile homes, independents

# M53a Pass 2 -- a peer sovereign sharing the home cluster: two mining
# colonies with their own trade routes, jurisdiction-seam bait for the
# pirate/warrant systems (design_ideas/m53a's "you killed someone in the
# next country over and nobody here cares"). "Meridian Combine" is a
# PLACEHOLDER name pending a real fiction-authoring pass -- do not treat it
# as settled lore. Crypto tag is TEAM_MERIDIAN (see home_cluster.gd).
const FLAG_MERIDIAN := "MERIDIAN_COMBINE"

const STRAY_HITS_TO_HOSTILE := 3          # third-party attribution confidence gate

# How long an aggression-bus event lingers before being pruned, in
# delta-accumulated seconds (same convention as ship.gd's outline-dot TTL --
# not wall-clock, so it stays deterministic under --fixed-fps). Comfortably
# longer than one sensor-fusion tick, so every ship processing this frame or
# the next few gets a chance to witness it.
const AGGRESSION_EVENT_TTL := 2.0

# Vessel classifications (Ship.classify_contact's own return strings) that
# standing applies to. Ordnance/wreckage/asteroid contacts always get
# standing "" -- PD and classification flows are untouched by this module.
const _VESSEL_CLASSIFICATIONS := ["FRIENDLY VESSEL", "UNIDENTIFIED VESSEL"]

# Severity order for datalink share's compare-and-copy (a peer's copy of a
# track only overrides mine if it's MORE severe). "" (no standing -- non-
# vessel, or a contact we haven't judged at all) sorts below every real tier.
const _SEVERITY := {
	"": -1,
	NEUTRAL: 0,
	UNREPORTED: 1,
	HOSTILE: 2,
}

static func severity(standing: String) -> int:
	return _SEVERITY.get(standing, -1)

static func is_more_severe(a: String, b: String) -> bool:
	return severity(a) > severity(b)

static func _iff_tags_overlap(tags_a: Array, tags_b: Array) -> bool:
	for tag in tags_a:
		if tags_b.has(tag):
			return true
	return false

# The pure resting-state rules, in precedence order (see the design doc's
# table for the full rationale of each tier). `contact` is an observer's own
# active_contacts entry (must carry "classification", may carry "signature",
# "standing"/"standing_reason" from a prior tick). `transponder` is the
# correlated active_transponders record for this track this tick (or {} if
# none received). `observer` is the Ship doing the judging (reads
# observer.iff_tags / observer.known_enemy_flags).
static func compute_standing(contact: Dictionary, transponder: Dictionary, observer) -> Dictionary:
	# Vessels only -- ordnance/wreckage/asteroid never carry a standing.
	var classification: String = contact.get("classification", "")
	if not _VESSEL_CLASSIFICATIONS.has(classification):
		return {"standing": "", "reason": ""}

	var sig: Dictionary = contact.get("signature", {})

	# 1. crypto: unforgeable IFF-tag handshake -> FRIENDLY.
	if _iff_tags_overlap(sig.get("iff_tags", []), observer.iff_tags):
		return {"standing": FRIENDLY, "reason": "IFF tag overlap"}

	var has_transponder: bool = not transponder.is_empty()
	var t_flag: String = transponder.get("flag", "") if has_transponder else ""
	var t_name: String = transponder.get("name", "") if has_transponder else ""

	# 2. M52b -- warrant-index lookup replaces the old sticky-HOSTILE rule.
	# An OPEN, unexpired, ENFORCEABLE-BY-US warrant naming this subject ->
	# HOSTILE. observer.warrant_index is rebuilt once per fusion tick (ship.gd)
	# from observer.warrants via Standing.build_warrant_index -- already
	# filtered to warrants this observer can enforce, so this is a plain O(1)
	# lookup, not a rule evaluation (design doc's settled Q3: "cheap per-
	# contact color lookup survives unchanged," only its input changed).
	var skey: String = subject_key(t_name, sig)
	var w: Dictionary = observer.warrant_index.get(skey, {})
	# 2026-07-26 -- fall back to the SIGNATURE key when the name key misses.
	# subject_key() files a warrant under "name:<claimed>" if a transponder name
	# was known at posting time and "sig:<tags>|<cross_section>" if it was not,
	# and nothing guarantees the two moments agree: a warrant posted while
	# active_transponders had no record for the subject is filed under `sig:`,
	# and once the transponder IS received every later lookup asks for `name:`
	# and misses FOREVER. The warrant is still in the index, just unreachable.
	#
	# Found by test_patrol_interdiction while decimating the datalink relay to
	# 10Hz (see Ship.DATALINK_RELAY_HZ): take_damage() posted an ASSAULT warrant
	# with claimed_name "" because the relay had not yet populated
	# active_transponders, and the next sensor recompute -- now holding the name
	# -- looked up the wrong key, found nothing, and overwrote take_damage()'s
	# eager HOSTILE stamp with NEUTRAL. The patrol then had no hostile contact
	# and never interdicted. NOT a cadence bug: the relay interval only widened
	# the race window from 1 frame to 6, which is what made it reproducible.
	# At 60Hz it was a one-frame window that the test happened never to land in.
	#
	# It is also a live gameplay hole, which is the real reason to fix it here
	# rather than paper over it in the relay: fire while dark, then light your
	# transponder, and the victim's assault warrant against you silently stops
	# applying. Turning a transponder ON should never launder a warrant.
	#
	# Deliberately ONE-DIRECTIONAL. The reverse case -- a warrant filed under
	# `name:` and looked up by signature after the subject goes dark -- is left
	# alone: that is designed behaviour (you cannot enforce a name warrant on a
	# hull you have not identified, matching the UNREPORTED/yellow rule), and
	# broadening name-keyed warrants to match by signature would let a warrant
	# against one ship apply to any hull sharing its tags and cross-section.
	#
	# EXCEPT for offenses that SELF-RESOLVE ON ID. NO_ID is the whole reason
	# this exception exists, and it is not an edge case -- the keying gap above
	# is literally NO_ID's resolution mechanism. A NO_ID warrant is filed under
	# `sig:` BY DEFINITION (the subject was not reporting a name; that IS the
	# offense), and warrants.md's taxonomy says it "resolves itself the moment
	# the subject reports a transponder -- compute_standing already flips them
	# off UNREPORTED on its own, so there is no separate revocation path to
	# build for it." That self-resolution worked precisely because the `name:`
	# lookup missed the `sig:`-keyed record. Falling back unconditionally would
	# have turned the cluster's most common, most forgivable offense into a
	# permanent HOSTILE brand that no code path can ever clear -- the exact
	# "enemy forever" failure the warrant model was built to retire.
	if w.is_empty() and t_name != "":
		var sig_w: Dictionary = observer.warrant_index.get(subject_key("", sig), {})
		if not self_resolves_on_id(sig_w.get("offense", "")):
			w = sig_w
	if not w.is_empty():
		var w_reason: String = w.get("reason", "")
		return {"standing": HOSTILE, "reason": w_reason if w_reason != "" else ("warrant: " + w.get("offense", ""))}

	# 3. flying a known-enemy flag -> HOSTILE, full stop (the one flag whose
	# meaning is never ambiguous).
	if has_transponder and t_flag != "" and observer.known_enemy_flags.has(t_flag):
		return {"standing": HOSTILE, "reason": "flying " + t_flag}

	# 4. transponder present (name + flag received, whatever their values --
	# an empty flag is itself a legitimate "no flag" declaration) -> NEUTRAL.
	# A claimed name being disliked by somebody does NOT change standing:
	# "suspicion" is not a standing (it has no shared meaning across roles),
	# it is the PATROL's own assessment (design_ideas/economy_and_piracy.md).
	# This comment used to point at a wanted-names registry as that
	# patrol-assessment input; that registry was deleted 2026-07-26 (see the
	# note where it used to live) because nothing ever read it.
	if has_transponder:
		return {"standing": NEUTRAL, "reason": "reporting clean"}

	# 5. no name+flag ever received for this track -> UNREPORTED. A location-
	# independent fact; enforcement response to it is location-dependent
	# (later milestone), the judgment itself is not.
	return {"standing": UNREPORTED, "reason": "not reporting"}

# --- Wanted-names registry: DELETED 2026-07-26 ------------------------------
# `wanted_names` (faction tag -> set of claimed names), `add_wanted` and
# `is_wanted` are gone. M48 introduced them; M52b's warrant model replaced
# what they were for, and the removal was overdue:
#
#   - `is_wanted` had ZERO production callers. compute_standing's own comment
#     claimed "is_wanted is called by the patrol tree (M52), not by this
#     classifier" -- the patrol tree did not call it either. Three sites
#     WROTE the registry (take_damage, and twice in the datalink relay's
#     standing share); nothing ever read it back.
#   - It was ambient process-global state: a name added by any ship was
#     visible to every ship sharing that faction tag, with no comms link, no
#     line of sight, no authority check and no expiry. That is exactly the
#     "ambient global truth" design_ideas/warrants.md set out to replace, and
#     it was the last unclearable "enemy forever" structure in the codebase.
#
# Per-observer `Ship.warrants` + `warrant_index` is the supported way to say
# "this observer holds something against that subject". If a patrol tree ever
# needs a suspicion input, derive it from warrants it can actually enforce --
# do not reintroduce a global set.
# See design_ideas/2026-07-26-warrant_stickiness_audit.md, mismatch 3.

# --- Aggression event bus ---------------------------------------------------
# Authority side (take_damage) posts one event per hit; observers consume
# events with seq > their own last_aggression_seq during fusion (ship.gd).
# victim_iff_tags/victim_name are snapshotted at post time (not re-derived
# from instance_from_id at consumption time) so a witness can judge the event
# even if the victim node is later freed.
static var aggression_events: Array = []
static var _aggression_seq: int = 0

# Frame-gate so the O(events) prune only actually mutates the array once per
# physics frame no matter how many ships call it during their own fusion tick
# this frame (every ship's tick wants pruning to have happened, but only one
# of them needs to do the work).
static var _last_prune_frame: int = -1

static func post_aggression(attacker_iid: int, victim_iid: int, pos: Vector2, victim_iff_tags: Array, victim_name: String) -> int:
	_aggression_seq += 1
	aggression_events.append({
		"seq": _aggression_seq,
		"attacker_iid": attacker_iid,
		"victim_iid": victim_iid,
		"pos": pos,
		"victim_iff_tags": victim_iff_tags.duplicate(),
		"victim_name": victim_name,
		"age": 0.0,
	})
	return _aggression_seq

static func prune_stale(delta: float) -> void:
	var frame := Engine.get_physics_frames()
	if frame == _last_prune_frame:
		return
	_last_prune_frame = frame
	var i := aggression_events.size() - 1
	while i >= 0:
		var ev: Dictionary = aggression_events[i]
		ev["age"] = ev.get("age", 0.0) + delta
		if ev["age"] > AGGRESSION_EVENT_TTL:
			aggression_events.remove_at(i)
		i -= 1

static func reset() -> void:
	aggression_events = []
	_aggression_seq = 0
	_last_prune_frame = -1

# --- Warrants (M52b) ---------------------------------------------------------
# Replaces sticky HOSTILE with observed, typed, revocable records. THE spec is
# design_ideas/warrants.md; the migration against this codebase is
# implementation_plans/m52b_warrants.md. Everything below is pure data +
# pure functions -- the STORE is per-ship (Ship.warrants/warrant_index/
# warrant_authority, ship.gd), never a Standing static (see the design doc's
# "not on the network -> you can't see it" visibility rule, and the plan's
# architecture note: a global static here would make that rule meaningless).
#
# Record shape (design doc's "Core model"):
#   offense, subject ({claimed_name, signature}), issuer ({iid, name}),
#   origin_flag, timestamp, expires, status, resolved_at, event_key, reason.
# `reason` is a small extension beyond the doc's literal schema -- free-text,
# human-readable (feeds contact["standing_reason"] the same way the old
# sticky-bit rule did), additive and harmless to the merge/dedup rules below.
#
# Time is the project's existing deterministic sim clock (Engine.get_physics_
# frames(), the same convention job_steps.gd's patience/blacklist timers use
# -- CLAUDE.md: --fixed-fps is deterministic, wall-clock is not). timestamp/
# expires/resolved_at are frame counts, not seconds; PHYSICS_HZ converts an
# offense's expiry duration (seconds, human-authored) to a frame count once,
# at post time.

const PHYSICS_HZ := 60.0

# --- Offense taxonomy v1 (design doc's table) --------------------------------
const OFF_ASSAULT := "ASSAULT"
const OFF_SUSTAINED_ASSAULT := "SUSTAINED_ASSAULT"
const OFF_ARMED_THREAT := "ARMED_THREAT"
const OFF_ARMED_ROBBERY := "ARMED_ROBBERY"
const OFF_NO_ID := "NO_ID"
const OFF_SPEED_VIOLATION := "SPEED_VIOLATION"
const OFF_OPERATOR_FLAGGED := "OPERATOR_FLAGGED"

const WARRANT_OPEN := "OPEN"
const WARRANT_RESOLVED := "RESOLVED"

# Response classes: both run the same challenge/demand/stand-down-or-fire
# shape, differing only in how much patience is extended (design doc's
# "Response levels"). MAX > INTERCEPT for the index's "worst matching
# warrant" tie-break.
const RESPONSE_INTERCEPT := "INTERCEPT"
const RESPONSE_MAX := "MAX"
const _RESPONSE_SEVERITY := {RESPONSE_INTERCEPT: 1, RESPONSE_MAX: 2}

# offense -> {response, expires_after_seconds (<0 = never)}. Values from the
# design doc's taxonomy table; NO_ID is self-resolving (not clock-based, see
# the doc) so it carries no clock expiry here either -- -1 means "never
# expires on its own clock", not "never resolved" (NO_ID still resolves via
# compute_standing's existing UNREPORTED-clearing rule, unrelated to this
# table).
#
# `self_resolves_on_id` marks an offense whose whole content is "you were not
# identifying yourself", so reporting a transponder ENDS it -- no clock, no
# revocation record. Only NO_ID qualifies. It exists as an explicit flag
# because the behaviour used to be implicit in a keying accident (a `sig:`-
# keyed warrant simply became unreachable once a `name:` lookup started being
# used), and compute_standing's signature fallback would otherwise have
# silently converted that accident into a permanent brand. Do not add this to
# ASSAULT and friends: shooting someone and then squawking is laundering, not
# resolution.
const _OFFENSE_TABLE := {
	OFF_ASSAULT: {"response": RESPONSE_INTERCEPT, "expires_after": 60.0},
	OFF_SUSTAINED_ASSAULT: {"response": RESPONSE_MAX, "expires_after": -1.0},
	OFF_ARMED_THREAT: {"response": RESPONSE_INTERCEPT, "expires_after": 1800.0},
	OFF_ARMED_ROBBERY: {"response": RESPONSE_MAX, "expires_after": -1.0},
	OFF_NO_ID: {"response": RESPONSE_INTERCEPT, "expires_after": -1.0, "self_resolves_on_id": true},
	OFF_SPEED_VIOLATION: {"response": RESPONSE_INTERCEPT, "expires_after": 60.0},
	OFF_OPERATOR_FLAGGED: {"response": RESPONSE_INTERCEPT, "expires_after": -1.0},
}

# True for an offense that ends when the subject starts reporting a
# transponder. See the table note above and warrants.md's NO_ID row.
static func self_resolves_on_id(offense: String) -> bool:
	return _OFFENSE_TABLE.get(offense, {}).get("self_resolves_on_id", false)

static func response_class(offense: String) -> String:
	return _OFFENSE_TABLE.get(offense, {}).get("response", RESPONSE_INTERCEPT)

static func response_severity(offense: String) -> int:
	return _RESPONSE_SEVERITY.get(response_class(offense), 0)

static func default_expiry_seconds(offense: String) -> float:
	return _OFFENSE_TABLE.get(offense, {}).get("expires_after", -1.0)

static func _now_frame() -> int:
	return Engine.get_physics_frames()

# v1 dedup rule (design doc): key on claimed transponder name when present,
# else on track-signature match -- "accept occasional duplicates over false
# merges." Same key shape Standing.wanted_names already uses (claimed name),
# extended with a signature fallback for dark/unclaimed subjects.
static func subject_key(claimed_name: String, signature: Dictionary) -> String:
	if claimed_name != "":
		return "name:" + claimed_name
	var tags: Array = signature.get("iff_tags", []).duplicate()
	tags.sort()
	return "sig:" + ",".join(tags) + "|" + str(signature.get("cross_section", 0.0))

static func warrant_subject_key(warrant: Dictionary) -> String:
	var subject: Dictionary = warrant.get("subject", {})
	return subject_key(subject.get("claimed_name", ""), subject.get("signature", {}))

# Issuing-authority origin-scoping (design doc's "Issuing authority" section):
# a ship's warrant only carries its own flag as origin_flag if that flag is
# one it's personally deputized to issue under (warrant_authority). Otherwise
# the warrant still posts, just scoped personal (origin_flag ""). ONE gate,
# routed through by every posting call site -- see warrant_enforceable_by
# below for the mirrored ENFORCEMENT half of the same rule.
static func scoped_origin(issuer_flag: String, issuer_authority: Array) -> String:
	if issuer_flag != "" and issuer_authority.has(issuer_flag):
		return issuer_flag
	return ""

static func make_warrant(offense: String, subject: Dictionary, issuer: Dictionary, origin_flag: String, event_key: String, reason: String = "") -> Dictionary:
	var now := _now_frame()
	var expires_after: float = default_expiry_seconds(offense)
	var expires: int = -1
	if expires_after > 0.0:
		expires = now + int(expires_after * PHYSICS_HZ)
	return {
		"offense": offense,
		"subject": subject.duplicate(true),
		"issuer": issuer.duplicate(true),
		"origin_flag": origin_flag,
		"timestamp": now,
		"expires": expires,
		"status": WARRANT_OPEN,
		"resolved_at": -1,
		"event_key": event_key,
		"reason": reason,
	}

# Revocation: a STATUS UPDATE to the SAME record, fresh timestamp (design
# doc's "Time limits and revocation") -- not an erase, so latest-timestamp-
# wins lets the resolution propagate over and override stale OPEN copies as
# it spreads. Returns a NEW dict (pure) -- callers assign it back.
static func resolve_warrant(warrant: Dictionary) -> Dictionary:
	var now := _now_frame()
	var out: Dictionary = warrant.duplicate(true)
	out["status"] = WARRANT_RESOLVED
	out["resolved_at"] = now
	out["timestamp"] = now
	return out

static func is_expired(warrant: Dictionary, now_frame: int = -1) -> bool:
	var expires: int = warrant.get("expires", -1)
	if expires < 0:
		return false
	var now: int = now_frame if now_frame >= 0 else _now_frame()
	return now >= expires

# Merge rule for both the datalink relay pass and the station pull (design
# doc: "latest-timestamp-wins is the merge rule"; plan: "latest-timestamp/
# highest-status-wins"). Returns whichever of a/b should be KEPT.
static func merge_warrant(a: Dictionary, b: Dictionary) -> Dictionary:
	var ta: int = a.get("timestamp", 0)
	var tb: int = b.get("timestamp", 0)
	if ta != tb:
		return a if ta > tb else b
	var a_resolved: bool = a.get("status", "") == WARRANT_RESOLVED
	var b_resolved: bool = b.get("status", "") == WARRANT_RESOLVED
	if a_resolved and not b_resolved:
		return a
	if b_resolved and not a_resolved:
		return b
	return a

# Authority chain (design doc): "enforcement and issuing share one gate."
# A personal-origin warrant (origin_flag == "") is, by construction, only
# ever found in its own issuer's OWN warrants store (the relay filter and the
# station-pull filter below both refuse to propagate an empty origin_flag) --
# so it is always enforceable by that same ship, the same private judgment
# today's per-observer sticky bit already amounted to. A flagged warrant
# (origin_flag != "") is enforceable by any ship holding that flag in its OWN
# warrant_authority -- the identical check scoped_origin used to decide
# whether to stamp the flag in the first place.
static func warrant_enforceable_by(warrant: Dictionary, observer_authority: Array, observer_iid: int) -> bool:
	var origin_flag: String = warrant.get("origin_flag", "")
	if origin_flag == "":
		return warrant.get("issuer", {}).get("iid", -1) == observer_iid
	return observer_authority.has(origin_flag)

# Per-observer subject-key -> worst enforceable OPEN warrant index (plan's
# architecture note: "rebuilt cheaply alongside" the warrant store, same key
# shape event_key's subject component uses). compute_standing does ONE dict
# lookup against this instead of reading a sticky bit -- only warrants THIS
# observer can actually enforce make it in, so a merely-visible (cross-flag
# or undeputized-witness) warrant never escalates standing to HOSTILE; it
# stays readable off the raw `warrants` store for informational/UI use
# (design doc: "still information, not noise... you just can't fire on the
# strength of it alone").
static func build_warrant_index(warrants: Dictionary, observer_authority: Array, observer_iid: int) -> Dictionary:
	var now := _now_frame()
	var index: Dictionary = {}
	for key in warrants:
		var w: Dictionary = warrants[key]
		if w.get("status", "") != WARRANT_OPEN:
			continue
		if is_expired(w, now):
			continue
		if not warrant_enforceable_by(w, observer_authority, observer_iid):
			continue
		var skey: String = warrant_subject_key(w)
		var existing: Dictionary = index.get(skey, {})
		if existing.is_empty():
			index[skey] = w
			continue
		var w_sev: int = response_severity(w.get("offense", ""))
		var e_sev: int = response_severity(existing.get("offense", ""))
		if w_sev > e_sev or (w_sev == e_sev and w.get("timestamp", 0) > existing.get("timestamp", 0)):
			index[skey] = w
	return index
