class_name Standing

# M48 -- Standings & flags (IFF v2). Static rules module: pure functions plus
# two small shared registries. No Node state -- everything per-observer lives
# on the observer ship's own contact records (contact["standing"]/
# ["standing_reason"]/["aggro_hits"], see ship.gd).
#
# Standing is FOUR tiers -- FRIENDLY / NEUTRAL / UNREPORTED / HOSTILE -- the
# dispositions that mean the SAME thing to every observer holding them, so
# they can ride the datalink and paint the contacts panel. "Suspicious" is
# deliberately NOT a standing: it has no shared meaning (a patrol's "acting
# like a predator" vs a pirate's "prey that might be a trap"), so it lives in
# each AI's own role-specific assessment (behavior-tree blackboard), never on
# the shared contact record. See design_ideas/economy_and_piracy.md.
#
# Reference this via the preload-const convention (see CLAUDE.md -- the
# git-tracked global class cache isn't regenerated by the headless --run-test
# path, so relying on the bare `Standing` global class name can fail to
# resolve until someone reopens the editor):
#   const Standing = preload("res://scripts/combat/standing.gd")
#
# See implementation_plans/m48_standings_flags_design.md (the file-pinned
# spec) and design_ideas/economy_and_piracy.md (the standing table + the
# three angle rules: assistance exemption, authority flags, attribution
# confidence gate) for the rule rationale this module implements.

const FRIENDLY := "FRIENDLY"
const NEUTRAL := "NEUTRAL"
const UNREPORTED := "UNREPORTED"
const HOSTILE := "HOSTILE"

const FLAG_PIRATE := "JOLLY_ROGER"
const FLAG_DRIFT := "SOVEREIGN_DRIFT"     # home faction / militia
const FLAG_CIVILIAN := "DRIFT_CIVILIAN"   # mobile homes, independents

const STRAY_HITS_TO_HOSTILE := 3          # third-party attribution confidence gate

# How long an aggression-bus event lingers before being pruned, in
# delta-accumulated seconds (same convention as ship.gd's outline-dot TTL --
# not wall-clock, so it stays deterministic under --fixed-fps). Comfortably
# longer than one sensor-fusion tick, so every ship processing this frame or
# the next few gets a chance to witness it.
const AGGRESSION_EVENT_TTL := 2.0

# Vessel classifications (Ship.classify_contact's own return strings) that
# standing applies to. Ordnance/wreckage/asteroid contacts always get
# standing "" -- PD and classification flows are untouched by this module.
const _VESSEL_CLASSIFICATIONS := ["FRIENDLY VESSEL", "UNIDENTIFIED VESSEL"]

# Severity order for datalink share's compare-and-copy (a peer's copy of a
# track only overrides mine if it's MORE severe). "" (no standing -- non-
# vessel, or a contact we haven't judged at all) sorts below every real tier.
const _SEVERITY := {
	"": -1,
	NEUTRAL: 0,
	UNREPORTED: 1,
	HOSTILE: 2,
}

static func severity(standing: String) -> int:
	return _SEVERITY.get(standing, -1)

static func is_more_severe(a: String, b: String) -> bool:
	return severity(a) > severity(b)

static func _iff_tags_overlap(tags_a: Array, tags_b: Array) -> bool:
	for tag in tags_a:
		if tags_b.has(tag):
			return true
	return false

# The pure resting-state rules, in precedence order (see the design doc's
# table for the full rationale of each tier). `contact` is an observer's own
# active_contacts entry (must carry "classification", may carry "signature",
# "standing"/"standing_reason" from a prior tick). `transponder` is the
# correlated active_transponders record for this track this tick (or {} if
# none received). `observer` is the Ship doing the judging (reads
# observer.iff_tags / observer.known_enemy_flags).
static func compute_standing(contact: Dictionary, transponder: Dictionary, observer) -> Dictionary:
	# Vessels only -- ordnance/wreckage/asteroid never carry a standing.
	var classification: String = contact.get("classification", "")
	if not _VESSEL_CLASSIFICATIONS.has(classification):
		return {"standing": "", "reason": ""}

	var sig: Dictionary = contact.get("signature", {})

	# 1. crypto: unforgeable IFF-tag handshake -> FRIENDLY.
	if _iff_tags_overlap(sig.get("iff_tags", []), observer.iff_tags):
		return {"standing": FRIENDLY, "reason": "IFF tag overlap"}

	# 2. sticky: existing HOSTILE on the track stays -- never recomputed away.
	if contact.get("standing", "") == HOSTILE:
		return {"standing": HOSTILE, "reason": contact.get("standing_reason", "")}

	var has_transponder: bool = not transponder.is_empty()
	var t_flag: String = transponder.get("flag", "") if has_transponder else ""

	# 3. flying a known-enemy flag -> HOSTILE, full stop (the one flag whose
	# meaning is never ambiguous).
	if has_transponder and t_flag != "" and observer.known_enemy_flags.has(t_flag):
		return {"standing": HOSTILE, "reason": "flying " + t_flag}

	# 4. transponder present (name + flag received, whatever their values --
	# an empty flag is itself a legitimate "no flag" declaration) -> NEUTRAL.
	# A claimed name on the faction wanted list does NOT change standing:
	# "suspicion" is not a standing (it has no shared meaning across roles),
	# it is the PATROL's own assessment (design_ideas/economy_and_piracy.md).
	# The wanted-names registry (below) stays as that patrol-assessment input;
	# is_wanted is called by the patrol tree (M52), not by this classifier.
	if has_transponder:
		return {"standing": NEUTRAL, "reason": "reporting clean"}

	# 5. no name+flag ever received for this track -> UNREPORTED. A location-
	# independent fact; enforcement response to it is location-dependent
	# (later milestone), the judgment itself is not.
	return {"standing": UNREPORTED, "reason": "not reporting"}

# --- Wanted-names registry -------------------------------------------------
# faction tag (String) -> Dictionary-as-set of claimed names. Static process
# state (shared by every ship in the running process) -- reset() for tests.
static var wanted_names: Dictionary = {}

static func add_wanted(tags: Array, claimed_name: String) -> void:
	if claimed_name == "":
		return
	for tag in tags:
		if not wanted_names.has(tag):
			wanted_names[tag] = {}
		wanted_names[tag][claimed_name] = true

static func is_wanted(tags: Array, claimed_name: String) -> bool:
	if claimed_name == "":
		return false
	for tag in tags:
		if wanted_names.get(tag, {}).has(claimed_name):
			return true
	return false

# --- Aggression event bus ---------------------------------------------------
# Authority side (take_damage) posts one event per hit; observers consume
# events with seq > their own last_aggression_seq during fusion (ship.gd).
# victim_iff_tags/victim_name are snapshotted at post time (not re-derived
# from instance_from_id at consumption time) so a witness can judge the event
# even if the victim node is later freed.
static var aggression_events: Array = []
static var _aggression_seq: int = 0

# Frame-gate so the O(events) prune only actually mutates the array once per
# physics frame no matter how many ships call it during their own fusion tick
# this frame (every ship's tick wants pruning to have happened, but only one
# of them needs to do the work).
static var _last_prune_frame: int = -1

static func post_aggression(attacker_iid: int, victim_iid: int, pos: Vector2, victim_iff_tags: Array, victim_name: String) -> int:
	_aggression_seq += 1
	aggression_events.append({
		"seq": _aggression_seq,
		"attacker_iid": attacker_iid,
		"victim_iid": victim_iid,
		"pos": pos,
		"victim_iff_tags": victim_iff_tags.duplicate(),
		"victim_name": victim_name,
		"age": 0.0,
	})
	return _aggression_seq

static func prune_stale(delta: float) -> void:
	var frame := Engine.get_physics_frames()
	if frame == _last_prune_frame:
		return
	_last_prune_frame = frame
	var i := aggression_events.size() - 1
	while i >= 0:
		var ev: Dictionary = aggression_events[i]
		ev["age"] = ev.get("age", 0.0) + delta
		if ev["age"] > AGGRESSION_EVENT_TTL:
			aggression_events.remove_at(i)
		i -= 1

static func reset() -> void:
	wanted_names = {}
	aggression_events = []
	_aggression_seq = 0
	_last_prune_frame = -1
