# M49 -- Hail protocol: structured machine-to-machine comms verbs
# (design_ideas/comms_verbs.md is THE SPEC; see also implementation_plans/
# m48_m55_economy_piracy_roadmap.md's "M49" section). Static module, same
# conventions as scripts/combat/standing.gd: verb/rung/nature string
# constants + pure-ish send functions + one small shared registry
# (hail_seq). No Node state of its own -- every hail lands on the
# RECEIVING ship's own comms_inbox (ship.gd), which owns all the
# interpretation (standing changes, pending_demand, compelled_stop, ...).
# hail.gd only owns the wire format + delivery.
#
# Reference this via the preload-const convention (see CLAUDE.md -- the
# git-tracked global class cache isn't regenerated by the headless
# --run-test path, so relying on a bare global class name can fail to
# resolve until someone reopens the editor):
#   const Hail = preload("res://scripts/comms/hail.gd")
#
# Delivery model: radio is a broadcast medium, not a point-to-point link.
# send()/send_broadcast() both walk get_tree().get_nodes_in_group("ships")
# ONCE and deliver an identical copy into every live receiver's comms_inbox
# that is within comms-link range of the SENDER -- same min(self, theirs)
# link rule the datalink relay uses (ship.gd's datalink_relay block,
# ~line 2340). No LOS requirement (omni radio, same as transponder
# receive). A DIRECTED send (send()) reaches bystanders too, exactly like a
# BROADCAST (send_broadcast()) -- the only difference is target_iid, which
# receiver-side processing uses to tell "addressed to me" from "overheard".
#
# hail.gd needs the scene tree to enumerate receivers; it reaches it via
# sender.get_tree(), so callers must pass a live Ship node as sender.

# --- Verbs ------------------------------------------------------------------
const VERB_DEMAND := "DEMAND"
# M52d -- renamed from COMPLY (playtest decision): the verb is a DECLARATION
# ("message received, holding station"), not the compliance itself --
# compliance stays behavioral (the receiver-side complied_stop contact field,
# which keeps its name; see implementation_plans/m52d_hail_ux.md item 3).
# M52d -- VERB_RELEASE removed entirely (design revised in review): under the
# channel model a demand/hold ends when the issuer stops refreshing it, so a
# dedicated "stop the demand" verb was redundant with the heartbeat itself.
const VERB_ACKNOWLEDGE := "ACKNOWLEDGE"
const VERB_SOS := "SOS"
const VERB_MARK_HOSTILE := "MARK_HOSTILE"

# --- DEMAND rungs -------------------------------------------------------------
const RUNG_IDENTIFY := "IDENTIFY"
const RUNG_STOP := "STOP"

# --- SOS natures --------------------------------------------------------------
const NATURE_UNDER_ATTACK := "UNDER_ATTACK"
const NATURE_DISABLED := "DISABLED"

# SOS must be sendable on minimal/battery power (a distress beacon survives a
# dead reactor even though the transponder didn't) -- a floor for SOS range,
# not a fallback triggered only when the comms component is fully dead.
# Revised (calling session, 2026-07-23): the old version only kicked in at
# get_comms_range() <= 0, so a comms component that was merely DAMAGED (down
# to, say, 5000u of its normal 30000u) still capped SOS at that reduced
# number -- "the consequence of a ship not being able to call for real help
# because of a damage roll is high, and that breaks the fun." Now SOS always
# gets AT LEAST this floor regardless of comms health, and a comms component
# that's still working for MORE than this range lets SOS ride that instead
# (a good working radio calls further than the battery backup, it just never
# calls LESS far). Receivers still need a working radio of their own to hear
# anything, SOS included -- this only relaxes the SENDER's requirement.
const SOS_BATTERY_RANGE := 30000.0

# Monotonically increasing across the whole process (not per-ship) -- gives
# ACKNOWLEDGE {in_reply_to} a value that disambiguates simultaneous demands
# from different issuers. reset() for tests (no cross-scenario bleed, same
# pattern as Standing.reset()).
static var hail_seq: int = 0

static func reset() -> void:
	hail_seq = 0

static func _next_seq() -> int:
	hail_seq += 1
	return hail_seq

# Directed send: target gets target_iid == its own instance id stamped on the
# copy it (and every bystander in range) receives. Returns the hail's seq, or
# -1 if the sender has no comms (silent failure -- a dark/reactor-dead ship
# just can't transmit, except SOS's battery exception below).
# M52d -- seq_override != -1 re-sends under an EXISTING seq (the demand
# heartbeat: a refresh of a live demand, not a new hail; receivers key
# refresh-vs-new on sender+seq). Default -1 draws a fresh seq as always.
static func send(sender, target, verb: Dictionary, seq_override: int = -1) -> int:
	if target == null or not is_instance_valid(target):
		return -1
	return _dispatch(sender, target.get_instance_id(), verb, seq_override)

# Undirected/broadcast send: target_iid == -1 on the delivered copy.
static func send_broadcast(sender, verb: Dictionary) -> int:
	return _dispatch(sender, -1, verb)

static func _dispatch(sender, target_iid: int, verb: Dictionary, seq_override: int = -1) -> int:
	if sender == null or not is_instance_valid(sender):
		return -1

	var is_sos: bool = verb.get("verb", "") == VERB_SOS
	var sender_range: float = sender.get_comms_range()
	if is_sos:
		sender_range = max(sender_range, SOS_BATTERY_RANGE) # battery floor, never a ceiling
	elif sender_range <= 0.0:
		return -1 # no working radio, no send -- not even an overheard copy

	var tree = sender.get_tree()
	if tree == null:
		return -1

	var seq := seq_override if seq_override != -1 else _next_seq()
	var transponder_data: Dictionary = sender.get_active_transponder_data()
	var hail: Dictionary = verb.duplicate(true)
	hail["seq"] = seq
	hail["sender_iid"] = sender.get_instance_id()
	hail["sender_pos"] = sender.position
	# Empty if dark -- a dark demand has no flag, that's the fiction
	# (design_ideas/comms_verbs.md).
	hail["sender_flag"] = transponder_data.get("flag", "")
	hail["sender_iff_tags"] = sender.iff_tags.duplicate()
	hail["target_iid"] = target_iid

	for s in tree.get_nodes_in_group("ships"):
		if s == sender:
			continue
		if not is_instance_valid(s) or s.is_dead:
			continue # a wreck has no ears
		if not s.has_method("get_comms_range"):
			continue
		var their_range: float = s.get_comms_range()
		if their_range <= 0.0:
			continue # receivers always need a working radio, SOS included
		var link_range: float = min(sender_range, their_range)
		if sender.position.distance_to(s.position) > link_range:
			continue
		s.comms_inbox.append(hail.duplicate(true))

	return seq
