class_name JobSteps

# M50 -- static executor library for the job runner (design_ideas/jobs_and_
# itineraries.md; implementation_plans/m50_pirate_tree_design.md pins the
# verb semantics below). One `step_<verb>(actor, step, job)` per verb,
# returning CONTINUE/DONE/ABORT. Executors are STATELESS -- any per-step
# scratch lives in `step["scratch"]` (a Dictionary the runner clears on entry
# to the step, including re-entry via an abort jump). `job` is the whole job
# dict (steps/current/repeat/victim_iid/...); most verbs ignore it, but
# SELECT_VICTIM/INTERCEPT/DEMAND_STOP/TAKE_ALONGSIDE share state (the
# selected victim's instance id) through job["victim_iid"], so every executor
# takes the same three-argument shape for a uniform dispatch table.
#
# Movement reuses the exact Steering.steer() + apply_control_input() idiom
# every existing leaf uses (flee_leaf.gd, cargo_run_leaf.gd, follow_route_
# leaf.gd) -- no new movement machinery.
#
# Reference via the preload-const convention (CLAUDE.md): the git-tracked
# global class cache isn't regenerated by the headless --run-test path, so a
# bare `JobSteps` reference can fail to resolve until someone reopens the
# editor.
#   const JobSteps = preload("res://scripts/ai/jobs/job_steps.gd")

const Steering = preload("res://scripts/ai/steering.gd")
const Standing = preload("res://scripts/combat/standing.gd")
const Hail = preload("res://scripts/comms/hail.gd")

const CONTINUE := 0
const DONE := 1
const ABORT := 2

# Ticks per second under this project's fixed physics step (CLAUDE.md:
# --fixed-fps 60 is deterministic and never sleeps). Frame-count elapsed-time
# tracking is the existing codebase idiom for AI-leaf timers (see challenge_
# leaf.gd's CHALLENGE_WINDOW_FRAMES/SCAN_INTERVAL_TICKS) -- leaves don't
# receive `delta`, only `actor`/`blackboard`, so frame counts stand in for
# delta-accumulated seconds.
const PHYSICS_HZ := 60.0

const SELECT_VICTIM_SCAN_INTERVAL := 30 # ticks -- per the design doc's "~30-tick-gated scoring"

# M52a: how long (frames) a failed-on victim is skipped by SELECT_VICTIM. A
# ship we demanded and couldn't take is alerted and running -- 90s of rest
# lets the hunt move to fresh prey instead of re-locking the same target.
const VICTIM_BLACKLIST_FRAMES := int(90.0 * PHYSICS_HZ)

# Stamp a victim onto the job's failure memory (SELECT_VICTIM reads it). Called
# from the demand/take aborts -- the victim refused or bolted, so give it a
# cooldown. Keyed by instance id; a no-op for an unknown id.
static func _blacklist_victim(job: Dictionary, iid: int) -> void:
	if iid == -1:
		return
	var bl: Dictionary = job.get("failed_victims", {})
	bl[iid] = Engine.get_physics_frames() + VICTIM_BLACKLIST_FRAMES
	job["failed_victims"] = bl

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

static func execute(verb: String, actor, step: Dictionary, job: Dictionary) -> int:
	match verb:
		"GO_TO":
			return step_go_to(actor, step, job)
		"GO_DARK":
			return step_go_dark(actor, step, job)
		"RELIGHT":
			return step_relight(actor, step, job)
		"LOITER_NEAR":
			return step_loiter_near(actor, step, job)
		"AWAIT":
			return step_await(actor, step, job)
		"DOCK_AT":
			return step_dock_at(actor, step, job)
		"EXIT_AT":
			return step_exit_at(actor, step, job)
		"SELECT_VICTIM":
			return step_select_victim(actor, step, job)
		"INTERCEPT":
			return step_intercept(actor, step, job)
		"DEMAND_STOP":
			return step_demand_stop(actor, step, job)
		"TAKE_ALONGSIDE":
			return step_take_alongside(actor, step, job)
		_:
			push_error("JobSteps.execute: unknown verb '%s'" % verb)
			return ABORT

# Runner-evaluated abort conditions (design doc's v1 "Abort conditions" list),
# cheap and ship-knowable. `cond` is one entry of a step's "abort_when" array:
# {"cond": String, "on_abort": String, <cond params>}.
static func check_abort(actor, job: Dictionary, cond: Dictionary) -> bool:
	match cond.get("cond", ""):
		"third_party_in_range":
			return _third_party_in_range(actor, job, cond.get("r", 5000.0))
		"victim_lost":
			return _victim_lost(actor, job)
		_:
			return false

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

static func _cruise_toward(actor, target: Vector2, exclude_pos, speed: float) -> void:
	var desired: Vector2 = target - actor.position
	if desired.length() > 0.01:
		desired = desired.normalized()
	var avoided: Vector2 = Steering.steer(actor, desired, exclude_pos)
	var desired_vel: Vector2 = avoided.normalized() * speed
	var steer: Vector2 = desired_vel - actor.linear_velocity
	if steer.length() < 10.0:
		steer = desired_vel
	actor.apply_control_input(0.0, speed, steer.angle(), 1, 1)

# Velocity mode with target_velocity 0.0 -- ACTIVELY brakes toward a stop
# (same idiom idle_leaf.gd uses), not a throttle-mode "zero thrust" coast.
# A coast was the bug here: closing on a target, then coasting once in
# range, sails straight through it with residual closing velocity and out
# the other side -- an orbiting overshoot that never settles long enough for
# TAKE_ALONGSIDE's hold timer (or SELECT_VICTIM/LOITER_NEAR's lurk) to
# accumulate.
static func _hold_station(actor) -> void:
	actor.apply_control_input(0.0, 0.0, actor.rotation, 0, 1)

static func _contact_for_instance(actor, iid: int) -> Dictionary:
	if iid == -1:
		return {}
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if c.get("instance_id", -1) == iid:
			return c
	return {}

static func _is_fresh(actor, c: Dictionary) -> bool:
	return not c.is_empty() and c.get("last_seen_timer", 999.0) <= actor.FIRE_STALENESS_MAX

static func _fresh_vessel_within(actor, r: float) -> bool:
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if not _is_fresh(actor, c):
			continue
		if not _VESSEL_CLASSIFICATIONS.has(c.get("classification", "")):
			continue
		if actor.position.distance_to(c.get("pos", actor.position)) <= r:
			return true
	return false

# Comms-hail range to a specific victim, honesty-compatible: resolves the
# live node purely to read ITS radio's range (the same "resolve the node to
# read its comms_range" idiom challenge_leaf.gd's _resolve_track_node already
# uses for an addressed hail), not to peek at any position/health/AI state.
# min(self, theirs), same rule Hail.send() itself applies -- with a small
# margin so the pirate settles just inside the boundary, not exactly on it.
static func _hail_range_to(actor, victim_iid: int) -> float:
	var self_range: float = actor.get_comms_range()
	var target = instance_from_id(victim_iid)
	var their_range: float = 0.0
	if target != null and is_instance_valid(target) and target.has_method("get_comms_range"):
		their_range = target.get_comms_range()
	if self_range <= 0.0 or their_range <= 0.0:
		return 0.0
	return min(self_range, their_range) * 0.9

static func _elapsed_seconds(scratch: Dictionary, key: String) -> float:
	var frame := Engine.get_physics_frames()
	if not scratch.has(key):
		scratch[key] = frame
	return (frame - scratch[key]) / PHYSICS_HZ

# ---------------------------------------------------------------------------
# GO_TO {pos, arrive_radius=1500.0, cruise=700.0}
# ---------------------------------------------------------------------------

static func step_go_to(actor, step: Dictionary, _job: Dictionary) -> int:
	var pos: Vector2 = step.get("pos", actor.position)
	var arrive_radius: float = step.get("arrive_radius", 1500.0)
	var cruise: float = step.get("cruise", 700.0)
	if actor.position.distance_to(pos) < arrive_radius:
		return DONE
	_cruise_toward(actor, pos, null, cruise)
	return CONTINUE

# ---------------------------------------------------------------------------
# GO_DARK {}
# ---------------------------------------------------------------------------

static func step_go_dark(actor, _step: Dictionary, _job: Dictionary) -> int:
	actor.set_transponder_active(false)
	return DONE

# ---------------------------------------------------------------------------
# RELIGHT {name, flag} -- or {from_kit: true, flag}: draw the next UNUSED
# identity paper from actor.identity_documents (the pre-provisioned kit --
# convincing papers take illegal back channels, they can't be fabricated on
# the spot). Kit exhausted -> ABORT (the job's on_abort decides what a
# paperless ship does -- the canonical hunt routes to a DARK run for the
# exit, hoping nobody stops it).
# ---------------------------------------------------------------------------

static func step_relight(actor, step: Dictionary, job: Dictionary) -> int:
	if step.get("from_kit", false):
		var doc = null
		for d in actor.identity_documents:
			if not d.get("used", false):
				doc = d
				break
		if doc == null:
			job["_abort_reason"] = "identity kit exhausted -- running dark"
			return ABORT # papers exhausted -- no identity left to fly
		doc["used"] = true
		if doc.get("name", "") != "":
			actor.set_transponder_custom_name(doc["name"])
		actor.set_transponder_flag(step.get("flag", doc.get("flag", "")))
		actor.set_transponder_active(true)
		return DONE

	var custom_name: String = step.get("name", "")
	if custom_name != "":
		actor.set_transponder_custom_name(custom_name)
	actor.set_transponder_flag(step.get("flag", ""))
	actor.set_transponder_active(true)
	return DONE

# ---------------------------------------------------------------------------
# LOITER_NEAR {pos, radius=2500.0, duration}
# ---------------------------------------------------------------------------

static func step_loiter_near(actor, step: Dictionary, _job: Dictionary) -> int:
	var pos: Vector2 = step.get("pos", actor.position)
	var radius: float = step.get("radius", 2500.0)
	var duration: float = step.get("duration", 0.0)
	var scratch: Dictionary = step.get("scratch", {})

	if _elapsed_seconds(scratch, "start_frame") >= duration:
		return DONE

	var to_center: Vector2 = pos - actor.position
	if to_center.length() > radius:
		_cruise_toward(actor, pos, null, 300.0)
	else:
		_hold_station(actor)
	return CONTINUE

# ---------------------------------------------------------------------------
# AWAIT {condition, timeout, ...}. v1 conditions: "duration" {seconds},
# "track_quiet" {seconds, clear_range}, "undocked" {}.
# ---------------------------------------------------------------------------

static func step_await(actor, step: Dictionary, _job: Dictionary) -> int:
	var scratch: Dictionary = step.get("scratch", {})
	var elapsed: float = _elapsed_seconds(scratch, "start_frame")

	# A wait means WAIT: brake and hold, don't keep sailing on whatever the
	# previous step's last cruise command was (a clear-wait that drifts at
	# cruise speed isn't waiting anywhere). Skipped while berthed -- the
	# capture spring owns motion there (AWAIT{undocked}).
	if actor.get("docking_bay") == null:
		_hold_station(actor)

	var condition: String = step.get("condition", "duration")
	var holds := false
	match condition:
		"duration":
			holds = elapsed >= step.get("seconds", 0.0)
		"track_quiet":
			holds = _track_quiet_holds(actor, step, scratch)
		"undocked":
			holds = actor.get("docking_bay") == null
		"clear":
			# No fresh VESSEL contact within clear_range -- "am I alone right
			# now?", read off the ship's own sensors (if I can't see them,
			# they likely can't see me -- the same honest heuristic as
			# track_quiet, minus its dark-transponder requirement). The hunt
			# job waits on this BEFORE going dark: a transponder that
			# vanishes in front of a watcher is a suspicion gift.
			holds = not _fresh_vessel_within(actor, step.get("clear_range", 8000.0))
		_:
			holds = false

	if holds:
		return DONE

	var timeout: float = step.get("timeout", -1.0)
	if timeout >= 0.0 and elapsed > timeout:
		return ABORT

	return CONTINUE

# The launder heuristic (design_ideas/jobs_and_itineraries.md's "honesty
# rule" worked example): dark AND holding no fresh contact within
# clear_range, continuously, for `seconds`. Resets to zero the instant either
# half breaks -- deliberately conservative/fallible, per the doc.
static func _track_quiet_holds(actor, step: Dictionary, scratch: Dictionary) -> bool:
	var seconds: float = step.get("seconds", 0.0)
	var clear_range: float = step.get("clear_range", 5000.0)

	var dark := true
	for c in actor.get_components_by_type("comms"):
		if c.get("transponder_active", true):
			dark = false
			break

	var fresh_contact_near := false
	if dark:
		for c_id in actor.active_contacts:
			var c: Dictionary = actor.active_contacts[c_id]
			if not _is_fresh(actor, c):
				continue
			if actor.position.distance_to(c.get("pos", actor.position)) <= clear_range:
				fresh_contact_near = true
				break

	var frame := Engine.get_physics_frames()
	if not dark or fresh_contact_near:
		scratch["quiet_since_frame"] = frame
		return false

	if not scratch.has("quiet_since_frame"):
		scratch["quiet_since_frame"] = frame
	var quiet_elapsed: float = (frame - scratch["quiet_since_frame"]) / PHYSICS_HZ
	return quiet_elapsed >= seconds

# ---------------------------------------------------------------------------
# DOCK_AT {station_pos} -- find the station near station_pos ("ships" group +
# get_berths(), cargo_run_leaf's _find_station_at pattern), request a grant at
# a controlled bay / raise wants_dock at an open one, DONE once captured.
# ---------------------------------------------------------------------------

const DOCK_STATION_SEARCH_RADIUS := 6000.0

static func step_dock_at(actor, step: Dictionary, _job: Dictionary) -> int:
	if actor.get("docking_bay") != null:
		return DONE

	var station_pos: Vector2 = step.get("station_pos", actor.position)
	var station = _find_station_near(actor, station_pos)

	if station == null:
		# Nothing to dock at (yet, or lost from wherever we got displaced to)
		# -- cruise toward the last-known position and keep retrying; a verb
		# must recover from arbitrary position, not assume it's still nearby.
		_cruise_toward(actor, station_pos, null, 700.0)
		return CONTINUE

	var zone: Dictionary = station.get_port_zone() if station.has_method("get_port_zone") else {}
	if not zone.is_empty():
		if actor.get("docking_grant") == null:
			station.issue_docking_grant(actor) # null (no berths) -- retry next tick
		if actor.get("docking_grant") != null:
			actor.wants_dock = true
	else:
		actor.wants_dock = true

	var berths: Array = station.get_berths() if station.has_method("get_berths") else []
	if berths.is_empty():
		_cruise_toward(actor, station.position, station.position, 700.0)
		return CONTINUE

	var target_berth = berths[0]
	var grant = actor.get("docking_grant")
	if grant != null and grant.get("slip_id", "") != "":
		for b in berths:
			if b.slip_id == grant.get("slip_id", ""):
				target_berth = b
				break

	var approach_pt: Vector2 = target_berth.global_position + Vector2.RIGHT.rotated(target_berth.global_rotation) * (target_berth.capture_radius * 0.8)
	_cruise_toward(actor, approach_pt, station.position, 700.0)
	return CONTINUE

static func _find_station_near(actor, pos: Vector2):
	var tree = actor.get_tree()
	if tree == null:
		return null
	var best = null
	var best_d: float = DOCK_STATION_SEARCH_RADIUS
	for s in tree.get_nodes_in_group("ships"):
		if s == actor:
			continue
		if not s.has_method("get_berths"):
			continue
		if s.get_berths().is_empty():
			continue
		var d: float = s.position.distance_to(pos)
		if d <= best_d:
			best = s
			best_d = d
	return best

# ---------------------------------------------------------------------------
# EXIT_AT {pos, radius=1500.0} -- GO_TO, then despawn.
# ---------------------------------------------------------------------------

static func step_exit_at(actor, step: Dictionary, _job: Dictionary) -> int:
	var pos: Vector2 = step.get("pos", actor.position)
	var radius: float = step.get("radius", 1500.0)
	if actor.position.distance_to(pos) < radius:
		actor.queue_free()
		return DONE
	_cruise_toward(actor, pos, null, step.get("cruise", 700.0))
	return CONTINUE

# ---------------------------------------------------------------------------
# SELECT_VICTIM {lane_pos, lurk_radius=2500.0, witness_range} -- pirate-only.
# Loiters near the lane; scores fresh vessel contacts every ~30 ticks. DONE
# stamps job["victim_iid"].
# ---------------------------------------------------------------------------

const _VESSEL_CLASSIFICATIONS := ["FRIENDLY VESSEL", "UNIDENTIFIED VESSEL"]

static func step_select_victim(actor, step: Dictionary, job: Dictionary) -> int:
	var lane_pos: Vector2 = step.get("lane_pos", actor.position)
	var lurk_radius: float = step.get("lurk_radius", 2500.0)
	var witness_range: float = step.get("witness_range", 5000.0)
	var scratch: Dictionary = step.get("scratch", {})

	# M52a withdraw budget -- two ceilings, whichever trips first:
	#   * attempts: each ENTRY to the hunt (scratch is cleared on entry, so a
	#     fresh scratch is a new victim-engagement cycle re-entered from a
	#     failed INTERCEPT/DEMAND/TAKE) counts one. Bounds a pirate that keeps
	#     FINDING prey but can't land a take (the campaign thrash).
	#   * time: a wall (frame) deadline set on the FIRST hunt entry. Bounds a
	#     pirate that finds NO prey at all and would otherwise lurk forever
	#     (never re-entering, so the attempt counter never advances) -- the
	#     lone-pirate-on-a-long-lane case the viability sim exposed.
	# Either exhausted -> abort to "exit": withdraw alive (-> RETURNED_EMPTY).
	var max_hunt_seconds: float = step.get("max_hunt_seconds", 0.0)
	if max_hunt_seconds > 0.0:
		if not job.has("hunt_deadline_frame"):
			job["hunt_deadline_frame"] = Engine.get_physics_frames() + int(max_hunt_seconds * PHYSICS_HZ)
		if Engine.get_physics_frames() > job["hunt_deadline_frame"]:
			job["_abort_reason"] = "hunt time budget (%.0fs) spent, no take -- withdrawing" % max_hunt_seconds
			return ABORT
	if not scratch.get("counted", false):
		scratch["counted"] = true
		job["hunt_attempts"] = job.get("hunt_attempts", 0) + 1
		var max_attempts: int = step.get("max_attempts", 0)
		if max_attempts > 0 and job["hunt_attempts"] > max_attempts:
			job["_abort_reason"] = "hunt budget spent (%d attempts, nothing taken) -- withdrawing" % (job["hunt_attempts"] - 1)
			return ABORT

	var to_lane: Vector2 = lane_pos - actor.position
	if to_lane.length() > lurk_radius:
		_cruise_toward(actor, lane_pos, null, 300.0)
	else:
		_hold_station(actor)

	var frame := Engine.get_physics_frames()
	var last_scan: int = scratch.get("last_scan_frame", -SELECT_VICTIM_SCAN_INTERVAL)
	if frame - last_scan < SELECT_VICTIM_SCAN_INTERVAL:
		return CONTINUE
	scratch["last_scan_frame"] = frame

	# Every fresh vessel contact (any standing) -- used for the ALONE check;
	# a witness is a witness regardless of what we've judged it.
	var all_fresh_vessels: Array = []
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if not _is_fresh(actor, c):
			continue
		if not _VESSEL_CLASSIFICATIONS.has(c.get("classification", "")):
			continue
		all_fresh_vessels.append(c)

	# Viable prey: NEUTRAL or UNREPORTED (never FRIENDLY-crypto, never
	# HOSTILE), and not currently complied (already someone else's mark --
	# the one ship-knowable proxy for "already being robbed/inspected").
	# M52a failure memory: skip a victim we recently failed on (job[
	# "failed_victims"][iid] holds a cooldown expiry frame) -- a ship we
	# already demanded is alerted and running, so re-picking it is the thrash
	# the campaign showed. Give it a rest and look for fresh prey.
	var blacklist: Dictionary = job.get("failed_victims", {})
	var now_frame := Engine.get_physics_frames()
	var candidates: Array = []
	for c in all_fresh_vessels:
		var standing: String = c.get("standing", "")
		if standing != Standing.NEUTRAL and standing != Standing.UNREPORTED:
			continue
		if c.get("complied_stop", false):
			continue
		if blacklist.get(c.get("instance_id", -1), 0) > now_frame:
			continue
		candidates.append(c)

	var viable: Array = []
	for c in candidates:
		var alone := true
		for other in all_fresh_vessels:
			if other == c:
				continue
			if c.get("pos", Vector2.ZERO).distance_to(other.get("pos", Vector2.ZERO)) <= witness_range:
				alone = false
				break
		if alone:
			viable.append(c)

	if viable.is_empty():
		return CONTINUE

	var best = viable[0]
	var best_cs: float = best.get("signature", {}).get("cross_section", INF)
	for c in viable:
		var cs: float = c.get("signature", {}).get("cross_section", INF)
		if cs < best_cs:
			best_cs = cs
			best = c

	job["victim_iid"] = best.get("instance_id", -1)
	return DONE

# ---------------------------------------------------------------------------
# INTERCEPT {} -- close on job["victim_iid"]'s track to inside comms-hail
# range, DONE there; ABORT if the track's gone stale (belt to the runner's
# own victim_lost abort_when, same "suspenders" idiom fire_opportunity_leaf
# uses alongside fire_weapon's own guard).
# ---------------------------------------------------------------------------

static func step_intercept(actor, step: Dictionary, job: Dictionary) -> int:
	var victim_iid: int = job.get("victim_iid", -1)
	var c: Dictionary = _contact_for_instance(actor, victim_iid)
	if not _is_fresh(actor, c):
		job["_abort_reason"] = "victim track lost"
		return ABORT

	var hail_range: float = _hail_range_to(actor, victim_iid)
	var dist: float = actor.position.distance_to(c.get("pos", actor.position))
	if hail_range > 0.0 and dist <= hail_range:
		return DONE

	var victim_pos: Vector2 = c.get("pos", actor.position)
	_cruise_toward(actor, victim_pos, victim_pos, step.get("cruise", 600.0))
	return CONTINUE

# ---------------------------------------------------------------------------
# DEMAND_STOP {show_colors=false, patience=25.0} -- send DEMAND(STOP) once;
# DONE when our own track on the victim shows complied_stop (M49 stamps this
# on COMPLY receipt); ABORT when outpaced beyond hail range or patience
# expires un-complied.
# ---------------------------------------------------------------------------

static func step_demand_stop(actor, step: Dictionary, job: Dictionary) -> int:
	var victim_iid: int = job.get("victim_iid", -1)
	var scratch: Dictionary = step.get("scratch", {})

	if step.get("show_colors", false) and not scratch.get("colors_shown", false):
		actor.set_transponder_flag(Standing.FLAG_PIRATE)
		actor.set_transponder_active(true)
		scratch["colors_shown"] = true

	var c: Dictionary = _contact_for_instance(actor, victim_iid)
	if c.is_empty():
		job["_abort_reason"] = "victim track lost"
		return ABORT

	if c.get("complied_stop", false):
		return DONE

	var victim_pos_demand: Vector2 = c.get("pos", actor.position)
	_cruise_toward(actor, victim_pos_demand, victim_pos_demand, step.get("cruise", 400.0))

	if not scratch.get("demand_sent", false):
		actor.send_demand(victim_iid, Hail.RUNG_STOP)
		scratch["demand_sent"] = true

	var patience: float = step.get("patience", 25.0)
	if _elapsed_seconds(scratch, "start_frame") > patience:
		job["_abort_reason"] = "patience %.0fs expired un-complied" % patience
		_blacklist_victim(job, victim_iid)
		return ABORT

	var hail_range: float = _hail_range_to(actor, victim_iid)
	var dist: float = actor.position.distance_to(c.get("pos", actor.position))
	if hail_range > 0.0 and dist > hail_range * 1.2:
		job["_abort_reason"] = "victim outpaced us beyond hail range (%.0f > %.0f)" % [dist, hail_range]
		_blacklist_victim(job, victim_iid)
		return ABORT # outpacing us beyond hail range -- let it go

	return CONTINUE

# ---------------------------------------------------------------------------
# TAKE_ALONGSIDE {hold_time=8.0, range=600.0} -- hold within range of the
# complied victim; accumulate ONLY while in range and still complied. DONE:
# loot_takes += 1, victim.looted = true, send RELEASE. ABORT if complied_stop
# clears (victim bolted).
# ---------------------------------------------------------------------------

static func step_take_alongside(actor, step: Dictionary, job: Dictionary) -> int:
	var victim_iid: int = job.get("victim_iid", -1)
	var scratch: Dictionary = step.get("scratch", {})
	var range: float = step.get("range", 600.0)
	var hold_time: float = step.get("hold_time", 8.0)

	var c: Dictionary = _contact_for_instance(actor, victim_iid)
	if c.is_empty() or not c.get("complied_stop", false):
		job["_abort_reason"] = "victim bolted (complied_stop cleared)"
		_blacklist_victim(job, victim_iid)
		return ABORT

	var victim_pos_take: Vector2 = c.get("pos", actor.position)
	var dist: float = actor.position.distance_to(victim_pos_take)
	if dist > range:
		_cruise_toward(actor, victim_pos_take, victim_pos_take, step.get("cruise", 300.0))
		scratch.erase("hold_start_frame") # only accumulate while actually in range
		return CONTINUE

	_hold_station(actor)

	var frame := Engine.get_physics_frames()
	if not scratch.has("hold_start_frame"):
		scratch["hold_start_frame"] = frame
	var held_elapsed: float = (frame - scratch["hold_start_frame"]) / PHYSICS_HZ
	if held_elapsed < hold_time:
		return CONTINUE

	actor.loot_takes += 1
	var victim = instance_from_id(victim_iid)
	if victim != null and is_instance_valid(victim):
		victim.looted = true
	actor.send_release(victim_iid)
	return DONE

# ---------------------------------------------------------------------------
# Abort condition helpers (shared, runner-evaluated).
# ---------------------------------------------------------------------------

# Any fresh UNIDENTIFIED VESSEL track that is neither the victim nor
# FRIENDLY, within r of ME. Per the design doc: "this is the pirate's own
# witness/patrol-closing read -- it cannot know a contact's ROLE, a witness
# is a witness."
static func _third_party_in_range(actor, job: Dictionary, r: float) -> bool:
	var victim_iid: int = job.get("victim_iid", -1)
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if not _is_fresh(actor, c):
			continue
		if c.get("classification", "") != "UNIDENTIFIED VESSEL":
			continue
		if c.get("instance_id", -1) == victim_iid:
			continue
		var d: float = actor.position.distance_to(c.get("pos", actor.position))
		if d <= r:
			# M52a: stamp WHO tripped the witness check so the abort log can
			# name it -- track id + range (the campaign log showed a bare
			# "third_party_in_range" with no way to tell a beacon from a patrol).
			job["_abort_reason"] = "witness %s at %.0f" % [c_id, d]
			return true
	return false

static func _victim_lost(actor, job: Dictionary) -> bool:
	var victim_iid: int = job.get("victim_iid", -1)
	if victim_iid == -1:
		return true
	return not _is_fresh(actor, _contact_for_instance(actor, victim_iid))
