class_name JobSteps

# M50 -- static executor library for the job runner (design_ideas/jobs_and_
# itineraries.md; implementation_plans/m50_pirate_tree_design.md pins the
# verb semantics below). One `step_<verb>(actor, step, job)` per verb,
# returning CONTINUE/DONE/ABORT. Executors are STATELESS -- any per-step
# scratch lives in `step["scratch"]` (a Dictionary the runner clears on entry
# to the step, including re-entry via an abort jump). `job` is the whole job
# dict (steps/current/repeat/victim_iid/...); most verbs ignore it, but
# SELECT_VICTIM/INTERCEPT/DEMAND_STOP/TAKE_ALONGSIDE share state (the
# selected victim's instance id) through job["victim_iid"], so every executor
# takes the same three-argument shape for a uniform dispatch table.
#
# Movement reuses the exact Steering.steer() + apply_control_input() idiom
# every existing leaf uses (flee_leaf.gd, cargo_run_leaf.gd, follow_route_
# leaf.gd) -- no new movement machinery.
#
# Reference via the preload-const convention (CLAUDE.md): the git-tracked
# global class cache isn't regenerated by the headless --run-test path, so a
# bare `JobSteps` reference can fail to resolve until someone reopens the
# editor.
#   const JobSteps = preload("res://scripts/ai/jobs/job_steps.gd")

const Steering = preload("res://scripts/ai/steering.gd")
const Standing = preload("res://scripts/combat/standing.gd")
const Hail = preload("res://scripts/comms/hail.gd")
# The docking corridor geometry. Until 2026-07-26 this was referenced only by
# navigation_panel.gd and exclusion_hatch.gd -- drawn for the player and flown
# by nobody. step_dock_at now reads it. See
# design_ideas/docking_approach_control.md.
const PortChannel = preload("res://scripts/port/port_channel.gd")
const Incident = preload("res://scripts/mail/incident.gd")

const CONTINUE := 0
const DONE := 1
const ABORT := 2

# Ticks per second under this project's fixed physics step (CLAUDE.md:
# --fixed-fps 60 is deterministic and never sleeps). Frame-count elapsed-time
# tracking is the existing codebase idiom for AI-leaf timers (see challenge_
# leaf.gd's CHALLENGE_WINDOW_FRAMES/SCAN_INTERVAL_TICKS) -- leaves don't
# receive `delta`, only `actor`/`blackboard`, so frame counts stand in for
# delta-accumulated seconds.
const PHYSICS_HZ := 60.0

const SELECT_VICTIM_SCAN_INTERVAL := 30 # ticks -- per the design doc's "~30-tick-gated scoring"

# M52d -- demand/hold heartbeat cadence (implementation_plans/m52d_hail_ux.md
# item 1, design revised in review: RELEASE removed, both DEMAND_STOP and
# TAKE_ALONGSIDE refresh the SAME seq via Ship.refresh_demand for as long as
# the pirate wants the demand/hold). A demand/hold is a channel the issuer
# keeps asserting; the victim clears it a few missed beats after the channel
# goes quiet (Ship.HAIL_HEARTBEAT_TIMEOUT = 6s, so a 2s cadence gives ~3
# missed beats of slack).
const DEMAND_REFRESH_FRAMES := int(2.0 * PHYSICS_HZ)

# M52c -- standoff intercept + speed-match hold (implementation_plans/
# m52c_robbery_mechanics.md items 1-2). The playtest's two failures were the
# same missing concept: no standoff distance (INTERCEPT drove straight at the
# victim's live position -- a ram waiting to happen against a moving victim)
# and no relative-velocity gate (DONE was pure proximity, so "intercept"
# could tag a moving target without ever matching its speed). INTERCEPT_
# STANDOFF_DIST sits in the design doc's 300-500u "flanking, not tailgating"
# band; INTERCEPT_SPEED_MATCH_THRESHOLD is comfortably under Ship's own
# COMPLIED_STOP_SPEED_LIMIT (80 u/s, ship.gd) -- an intercept "matched" at 50
# u/s of relative speed reads as alongside, not a flyby.
const INTERCEPT_STANDOFF_DIST := 400.0
const INTERCEPT_SPEED_MATCH_THRESHOLD := 50.0

# Position-catchup gain for _pace_at_offset -- u/s of closing speed commanded
# per u of distance from the pace target, clamped to the caller's cruise cap.
# Large enough to saturate at "cruise" well outside the standoff band (so a
# distant approach still reads as a normal cruise-in), small enough to taper
# smoothly into a matched-velocity hold as the gap closes instead of
# overshooting through it.
const PACE_POSITION_GAIN := 0.6

# Derates the sqrt braking profile's assumed accel below the ship's raw
# thrust/mass -- the profile assumes the ship is ALREADY thrusting at full
# accel exactly opposite its velocity error every tick, but turning to face
# that direction (and the velocity-control PID chasing a rapidly-shrinking
# target) both lag a tick or more behind a perfectly instantaneous response.
# Empirically tuned against a throwaway debug trace: 1.0 (no derate)
# consistently overshot the pace target and only satisfied the speed-match
# threshold well past it, almost on top of the victim; this factor pulls the
# "start slowing down" point earlier so the real (laggy) ship can actually
# hold the curve.
const PACE_BRAKING_SAFETY := 0.3

# Hysteresis on TAKE_ALONGSIDE's in-range check -- see the step's own header
# comment for why a bare "dist > range" cutoff isn't enough once the hold
# envelope is tight.
const TAKE_ALONGSIDE_EXIT_SLACK := 1.25

# M52 playtest fix -- thermal governor for _pace_at_offset (calling session,
# 2026-07-22): two pirates converging on the SAME victim never exclude EACH
# OTHER from Steering.steer's avoidance (only the victim is excluded), so
# their pacing math and their mutual anti-overlap push fight indefinitely --
# neither ever settles, both hold near-max commanded speed forever. That's
# real heat: _engine_heat_contribution scales with abs(throttle), and once
# current_heat pegs at max_heat, ship.gd's OWN periodic check drains the
# reactor's health directly (10 HP/s) -- a path that never goes through
# take_damage(), so it produced zero [Damage] print, zero collision, and no
# last_damage_attacker_name -- a pirate simply died mid-encounter with no
# visible cause. Confirmed empirically: 2 pirates vs. 1 complying victim,
# heat climbed 0 -> 140/140 in ~35s at throttle 0.7-1.0, reactor cooked to 0
# HP by ~48s.
#
# Fix: _pace_at_offset now derates its OWN catchup surge as the actor's own
# current_heat climbs, so no matter what's fighting it (another pirate's
# avoidance, a target that never converges, anything), it can never hold
# near-max commanded speed indefinitely -- it eases off well before
# current_heat ever reaches max_heat, giving passive/active dissipation room
# to work, self-stabilizing instead of pegging and taking reactor damage.
# Below HEAT_SAFE_RATIO: no effect (normal single-target pacing, already
# proven convergent by test_robbery_mechanics, is untouched). Above it:
# linear derate to 0 at max_heat -- a ship that's ALREADY overheated (from
# combat, not just maneuvering) coasts to a stop rather than adding more.
const HEAT_SAFE_RATIO := 0.75

# M52a: how long (frames) a failed-on victim is skipped by SELECT_VICTIM. A
# ship we demanded and couldn't take is alerted and running -- 90s of rest
# lets the hunt move to fresh prey instead of re-locking the same target.
const VICTIM_BLACKLIST_FRAMES := int(90.0 * PHYSICS_HZ)

# Stamp a victim onto the job's failure memory (SELECT_VICTIM reads it). Called
# from the demand/take aborts -- the victim refused or bolted, so give it a
# cooldown. Keyed by instance id; a no-op for an unknown id.
static func _blacklist_victim(job: Dictionary, iid: int) -> void:
	if iid == -1:
		return
	var bl: Dictionary = job.get("failed_victims", {})
	bl[iid] = Engine.get_physics_frames() + VICTIM_BLACKLIST_FRAMES
	job["failed_victims"] = bl

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

static func execute(verb: String, actor, step: Dictionary, job: Dictionary) -> int:
	match verb:
		"GO_TO":
			return step_go_to(actor, step, job)
		"GO_DARK":
			return step_go_dark(actor, step, job)
		"RELIGHT":
			return step_relight(actor, step, job)
		"LOITER_NEAR":
			return step_loiter_near(actor, step, job)
		"AWAIT":
			return step_await(actor, step, job)
		"DOCK_AT":
			return step_dock_at(actor, step, job)
		"EXIT_AT":
			return step_exit_at(actor, step, job)
		"SELECT_VICTIM":
			return step_select_victim(actor, step, job)
		"INTERCEPT":
			return step_intercept(actor, step, job)
		"DEMAND_STOP":
			return step_demand_stop(actor, step, job)
		"TAKE_ALONGSIDE":
			return step_take_alongside(actor, step, job)
		_:
			push_error("JobSteps.execute: unknown verb '%s'" % verb)
			return ABORT

# Runner-evaluated abort conditions (design doc's v1 "Abort conditions" list),
# cheap and ship-knowable. `cond` is one entry of a step's "abort_when" array:
# {"cond": String, "on_abort": String, <cond params>}.
static func check_abort(actor, job: Dictionary, cond: Dictionary) -> bool:
	match cond.get("cond", ""):
		"third_party_in_range":
			return _third_party_in_range(actor, job, cond.get("r", 5000.0))
		"victim_lost":
			return _victim_lost(actor, job)
		_:
			return false

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

static func _cruise_toward(actor, target: Vector2, exclude_pos, speed: float) -> void:
	var desired: Vector2 = target - actor.position
	if desired.length() > 0.01:
		desired = desired.normalized()
	var avoided: Vector2 = Steering.steer(actor, desired, exclude_pos)
	# Approach discipline + published port limits (design_ideas/
	# port_zones_and_channels.md "Two speed rules, not one"). Applied HERE
	# because this is the single choke point every job-driven mover already
	# funnels through, so GO_TO/DOCK_AT/intercept all inherit it without each
	# growing its own copy of the rule.
	speed = Steering.approach_speed_limit(actor, speed)
	var desired_vel: Vector2 = avoided.normalized() * speed
	var steer: Vector2 = desired_vel - actor.linear_velocity
	if steer.length() < 10.0:
		steer = desired_vel
	# Tell the hull whether this is an emergency. The thermal self-throttle
	# itself lives on Ship (it must cover combat leaves and every other mover,
	# not just job verbs); all this does is raise its floor when a dodge is
	# actually pressing.
	#
	# Steering.last_urgency is set by the _avoidance() call made just above and
	# MUST be read immediately -- it is static scratch, valid only until the next
	# ship steers (see steering.gd). This is exactly that moment.
	actor.throttle_emergency = Steering.last_urgency >= URGENT_THROTTLE_RELEASE
	actor.apply_control_input(0.0, speed, steer.angle(), 1, 1)

# Velocity mode with target_velocity 0.0 -- ACTIVELY brakes toward a stop
# (same idiom idle_leaf.gd uses), not a throttle-mode "zero thrust" coast.
# A coast was the bug here: closing on a target, then coasting once in
# range, sails straight through it with residual closing velocity and out
# the other side -- an orbiting overshoot that never settles long enough for
# TAKE_ALONGSIDE's hold timer (or SELECT_VICTIM/LOITER_NEAR's lurk) to
# accumulate.
static func _hold_station(actor) -> void:
	actor.apply_control_input(0.0, 0.0, actor.rotation, 0, 1)

# M52c -- a perpendicular offset from the victim's own heading (its velocity
# vector, while it has way on; falls back to the last-known heading, then to
# the actor's own bearing to the victim, for a victim sitting dead still with
# no prior heading) -- "abeam", not dead ahead/behind, so a closing approach
# reads as a flanking pass, not a tailgate. Which SIDE is picked once, the
# first time this is called for the step's current run (`scratch` is cleared
# on entry to the step -- job_runner_leaf.gd -- so this re-decides on every
# fresh entry), from the actor's OWN current bearing to the victim at that
# moment, so the approach doesn't have to loop around to reach its own side.
static func _standoff_offset(actor, victim_pos: Vector2, victim_vel: Vector2, dist: float, scratch: Dictionary) -> Vector2:
	var heading_dir: Vector2
	if victim_vel.length() > 1.0:
		heading_dir = victim_vel.normalized()
	elif scratch.has("standoff_heading"):
		heading_dir = scratch["standoff_heading"]
	elif actor.position.distance_to(victim_pos) > 0.01:
		heading_dir = (victim_pos - actor.position).normalized()
	else:
		heading_dir = Vector2.RIGHT
	scratch["standoff_heading"] = heading_dir

	var perp: Vector2 = Vector2(-heading_dir.y, heading_dir.x)
	if not scratch.has("standoff_side"):
		var to_actor: Vector2 = actor.position - victim_pos
		scratch["standoff_side"] = 1.0 if perp.dot(to_actor) >= 0.0 else -1.0
	return perp * scratch["standoff_side"] * dist

# M52c -- shared "flank and match" steering for INTERCEPT/DEMAND_STOP's
# approach and TAKE_ALONGSIDE's hold (implementation_plans/
# m52c_robbery_mechanics.md item 2): steer toward target_pos (typically the
# victim's position plus a _standoff_offset) while CARRYING the victim's own
# velocity, not just chasing its raw position the way _cruise_toward does.
# Position error contributes a catch-up term (clamped to `cruise`) on top of
# target_vel, so a big gap surges to close it and a small one settles into
# riding along at the victim's own speed -- a complying (decelerating)
# victim naturally becomes a stationary alongside as its velocity drops, with
# no separate "arrived, switch to holding" branch needed. Same steer-then-
# apply_control_input idiom _cruise_toward uses (velocity-mode, Combat
# steering); `exclude_pos` follows Steering.steer's own contract and is
# always the victim's own position here, same as every existing _cruise_
# toward call this file made against a victim -- the offset target point
# (never the victim's own position) is what keeps the approach clear of the
# hull, not generic obstacle avoidance. Passing the victim itself through
# avoidance instead would fight this: Steering's own anti-overlap "safe"
# radius (bounding radii + its 400u MARGIN, steering.gd) comfortably exceeds
# a several-hundred-unit standoff, so an un-excluded victim reads as an
# obstacle to shove away from right as the approach is trying to settle
# there, and the two forces fight forever instead of converging.
#
# Catch-up speed profile: sqrt(2 * a_max * dist), the same time-optimal
# "square-root braking curve" idea ship.gd's own rotation controller already
# uses (its header comment: "Time-Optimal Rotational Controller (Square-root
# curve braking)"), mirrored here for translation. A first pass used a plain
# LINEAR ramp (speed proportional to distance, clamped to `cruise`); a
# throwaway debug trace caught it overshooting the pace target every single
# approach and orbiting for 30-60+ real seconds before a lucky pass finally
# landed under the speed-match threshold -- a linear ramp only starts
# shedding speed once inside `cruise / PACE_POSITION_GAIN`, which is
# nowhere near enough room for the ship to actually stop given its real
# thrust/mass deceleration, so it always arrived at the target still going
# too fast. sqrt(2*a_max*dist) IS the stopping-distance-correct speed for a
# ship that decelerates at a_max the whole way in -- no overshoot by
# construction, confirmed against the same debug trace before landing this.
# Linear derate 1.0 -> 0.0 as actor.current_heat climbs from HEAT_SAFE_RATIO
# to max_heat. 1.0 (no effect) below the safe ratio or for a heatless/
# max_heat<=0 actor (defensive -- every catalog hull has a reactor, but a
# bare test fixture might not).
static func _thermal_derate(actor) -> float:
	var max_heat: float = actor.max_heat
	if max_heat <= 0.0:
		return 1.0
	var ratio: float = actor.current_heat / max_heat
	if ratio <= HEAT_SAFE_RATIO:
		return 1.0
	return clampf(1.0 - (ratio - HEAT_SAFE_RATIO) / (1.0 - HEAT_SAFE_RATIO), 0.0, 1.0)

static func _pace_at_offset(actor, target_pos: Vector2, target_vel: Vector2, exclude_pos, cruise: float) -> void:
	var to_target: Vector2 = target_pos - actor.position
	var dist: float = to_target.length()
	var accel_max: float = (actor.get_ship_max_thrust() / actor.mass) if actor.mass > 0.0 else 0.0
	var catchup: float
	if accel_max > 0.0:
		catchup = clampf(sqrt(2.0 * accel_max * PACE_BRAKING_SAFETY * dist), 0.0, cruise)
	else:
		catchup = clampf(dist * PACE_POSITION_GAIN, 0.0, cruise) # fallback: no engines to derive a braking curve from
	catchup *= _thermal_derate(actor)
	var dir: Vector2 = to_target.normalized() if dist > 0.01 else Vector2.ZERO
	var avoided: Vector2 = Steering.steer(actor, dir, exclude_pos)
	var desired_vel: Vector2 = target_vel + avoided.normalized() * catchup

	var steer: Vector2 = desired_vel - actor.linear_velocity
	var heading: float
	if steer.length() >= 10.0:
		heading = steer.angle()
	elif desired_vel.length() > 1.0:
		heading = desired_vel.angle()
	else:
		heading = actor.rotation
	actor.apply_control_input(0.0, desired_vel.length(), heading, 1, 1)

static func _contact_for_instance(actor, iid: int) -> Dictionary:
	if iid == -1:
		return {}
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if c.get("instance_id", -1) == iid:
			return c
	return {}

static func _is_fresh(actor, c: Dictionary) -> bool:
	return not c.is_empty() and Ship.contact_age(c) <= actor.FIRE_STALENESS_MAX

static func _fresh_vessel_within(actor, r: float) -> bool:
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if not _is_fresh(actor, c):
			continue
		if not Standing.is_vessel(c.get("classification", "")):
			continue
		if actor.position.distance_to(c.get("pos", actor.position)) <= r:
			return true
	return false

# Comms-hail range to a specific victim, honesty-compatible: resolves the
# live node purely to read ITS radio's range (the same "resolve the node to
# read its comms_range" idiom challenge_leaf.gd's _resolve_track_node already
# uses for an addressed hail), not to peek at any position/health/AI state.
# min(self, theirs), same rule Hail.send() itself applies -- with a small
# margin so the pirate settles just inside the boundary, not exactly on it.
static func _hail_range_to(actor, victim_iid: int) -> float:
	var self_range: float = actor.get_comms_range()
	var target = instance_from_id(victim_iid)
	var their_range: float = 0.0
	if target != null and is_instance_valid(target) and target.has_method("get_comms_range"):
		their_range = target.get_comms_range()
	if self_range <= 0.0 or their_range <= 0.0:
		return 0.0
	return min(self_range, their_range) * 0.9

static func _elapsed_seconds(scratch: Dictionary, key: String) -> float:
	var frame := Engine.get_physics_frames()
	if not scratch.has(key):
		scratch[key] = frame
	return (frame - scratch[key]) / PHYSICS_HZ

# ---------------------------------------------------------------------------
# GO_TO {pos, arrive_radius=1500.0, cruise=700.0}
# ---------------------------------------------------------------------------

static func step_go_to(actor, step: Dictionary, _job: Dictionary) -> int:
	var pos: Vector2 = step.get("pos", actor.position)
	var arrive_radius: float = step.get("arrive_radius", 1500.0)
	var cruise: float = step.get("cruise", 700.0)
	if actor.position.distance_to(pos) < arrive_radius:
		return DONE
	_cruise_toward(actor, pos, null, cruise)
	return CONTINUE

# ---------------------------------------------------------------------------
# GO_DARK {}
# ---------------------------------------------------------------------------

static func step_go_dark(actor, _step: Dictionary, _job: Dictionary) -> int:
	actor.set_transponder_active(false)
	return DONE

# ---------------------------------------------------------------------------
# RELIGHT {name, flag} -- or {from_kit: true, flag}: draw the next UNUSED
# identity paper from actor.identity_documents (the pre-provisioned kit --
# convincing papers take illegal back channels, they can't be fabricated on
# the spot). Kit exhausted -> ABORT (the job's on_abort decides what a
# paperless ship does -- the canonical hunt routes to a DARK run for the
# exit, hoping nobody stops it).
# ---------------------------------------------------------------------------

static func step_relight(actor, step: Dictionary, job: Dictionary) -> int:
	if step.get("from_kit", false):
		var doc = null
		for d in actor.identity_documents:
			if not d.get("used", false):
				doc = d
				break
		if doc == null:
			job["_abort_reason"] = "identity kit exhausted -- running dark"
			return ABORT # papers exhausted -- no identity left to fly
		doc["used"] = true
		if doc.get("name", "") != "":
			actor.set_transponder_custom_name(doc["name"])
		actor.set_transponder_flag(step.get("flag", doc.get("flag", "")))
		actor.set_transponder_active(true)
		return DONE

	var custom_name: String = step.get("name", "")
	if custom_name != "":
		actor.set_transponder_custom_name(custom_name)
	actor.set_transponder_flag(step.get("flag", ""))
	actor.set_transponder_active(true)
	return DONE

# ---------------------------------------------------------------------------
# LOITER_NEAR {pos, radius=2500.0, duration}
# ---------------------------------------------------------------------------

static func step_loiter_near(actor, step: Dictionary, _job: Dictionary) -> int:
	var pos: Vector2 = step.get("pos", actor.position)
	var radius: float = step.get("radius", 2500.0)
	var duration: float = step.get("duration", 0.0)
	var scratch: Dictionary = step.get("scratch", {})

	if _elapsed_seconds(scratch, "start_frame") >= duration:
		return DONE

	var to_center: Vector2 = pos - actor.position
	if to_center.length() > radius:
		_cruise_toward(actor, pos, null, 300.0)
	else:
		_hold_station(actor)
	return CONTINUE

# ---------------------------------------------------------------------------
# AWAIT {condition, timeout, ...}. v1 conditions: "duration" {seconds},
# "track_quiet" {seconds, clear_range}, "undocked" {}.
# ---------------------------------------------------------------------------

static func step_await(actor, step: Dictionary, _job: Dictionary) -> int:
	var scratch: Dictionary = step.get("scratch", {})
	var elapsed: float = _elapsed_seconds(scratch, "start_frame")

	# A wait means WAIT: brake and hold, don't keep sailing on whatever the
	# previous step's last cruise command was (a clear-wait that drifts at
	# cruise speed isn't waiting anywhere). Skipped while berthed -- the
	# capture spring owns motion there (AWAIT{undocked}).
	if actor.get("docking_bay") == null:
		_hold_station(actor)

	var condition: String = step.get("condition", "duration")
	var holds := false
	match condition:
		"duration":
			holds = elapsed >= step.get("seconds", 0.0)
		"track_quiet":
			holds = _track_quiet_holds(actor, step, scratch)
		"undocked":
			holds = actor.get("docking_bay") == null
		"clear":
			# No fresh VESSEL contact within clear_range -- "am I alone right
			# now?", read off the ship's own sensors (if I can't see them,
			# they likely can't see me -- the same honest heuristic as
			# track_quiet, minus its dark-transponder requirement). The hunt
			# job waits on this BEFORE going dark: a transponder that
			# vanishes in front of a watcher is a suspicion gift.
			holds = not _fresh_vessel_within(actor, step.get("clear_range", 8000.0))
		_:
			holds = false

	if holds:
		return DONE

	var timeout: float = step.get("timeout", -1.0)
	if timeout >= 0.0 and elapsed > timeout:
		return ABORT

	return CONTINUE

# The launder heuristic (design_ideas/jobs_and_itineraries.md's "honesty
# rule" worked example): dark AND holding no fresh contact within
# clear_range, continuously, for `seconds`. Resets to zero the instant either
# half breaks -- deliberately conservative/fallible, per the doc.
static func _track_quiet_holds(actor, step: Dictionary, scratch: Dictionary) -> bool:
	var seconds: float = step.get("seconds", 0.0)
	var clear_range: float = step.get("clear_range", 5000.0)

	var dark := true
	for c in actor.get_components_by_type("comms"):
		if c.get("transponder_active", true):
			dark = false
			break

	var fresh_contact_near := false
	if dark:
		for c_id in actor.active_contacts:
			var c: Dictionary = actor.active_contacts[c_id]
			if not _is_fresh(actor, c):
				continue
			if actor.position.distance_to(c.get("pos", actor.position)) <= clear_range:
				fresh_contact_near = true
				break

	var frame := Engine.get_physics_frames()
	if not dark or fresh_contact_near:
		scratch["quiet_since_frame"] = frame
		return false

	if not scratch.has("quiet_since_frame"):
		scratch["quiet_since_frame"] = frame
	var quiet_elapsed: float = (frame - scratch["quiet_since_frame"]) / PHYSICS_HZ
	return quiet_elapsed >= seconds

# ---------------------------------------------------------------------------
# DOCK_AT {station_pos, delivery={acceptance, amount} (opt)} -- find the
# station near station_pos ("ships" group + get_berths(), cargo_run_leaf's
# _find_station_at pattern), request a grant at a controlled bay / raise
# wants_dock at an open one, DONE once captured.
#
# M53c Phase C -- optional `delivery` stages a cargo transaction on the actor
# (Ship.pending_delivery) the FIRST tick this step is entered, well before
# capture completes: docking_bay.gd's own DOCKED-transition hook is what
# actually settles it later (Part 1's delivery seam), this step only needs to
# hand it off once. Guarded by scratch (cleared on entry, per job_runner_
# leaf.gd) so a multi-tick TRANSIT phase doesn't re-stage every frame.
# ---------------------------------------------------------------------------

const DOCK_STATION_SEARCH_RADIUS := 6000.0

# Seconds of travel used as the LOS lookahead on a docking run (see the
# guidance block in step_dock_at). Half of Steering.LOOKAHEAD_TIME, which is the
# codebase's existing "long enough that a heavy hull has room to swing clear"
# figure -- converging onto a line the hull is already near needs less room than
# dodging an obstacle it is closing on.
const LOS_LOOKAHEAD_TIME := 3.0

# Avoidance urgency (Steering.last_urgency, 0..1) at which a mover declares a
# thermal emergency, raising the hull's self-throttle floor (Ship's
# THERMAL_EMERGENCY_FLOOR -- it never removes the limit). Mid-scale on purpose:
# a hull should be spending hard well before a dodge becomes desperate.
const URGENT_THROTTLE_RELEASE := 0.5

static func step_dock_at(actor, step: Dictionary, _job: Dictionary) -> int:
	var scratch: Dictionary = step.get("scratch", {})
	var delivery: Dictionary = step.get("delivery", {})
	if not delivery.is_empty() and not scratch.get("delivery_staged", false):
		actor.pending_delivery = delivery.duplicate(true)
		scratch["delivery_staged"] = true

	if actor.get("docking_bay") != null:
		return DONE

	var station_pos: Vector2 = step.get("station_pos", actor.position)
	var station = _find_station_near(actor, station_pos)

	if station == null:
		# Nothing to dock at (yet, or lost from wherever we got displaced to)
		# -- cruise toward the last-known position and keep retrying; a verb
		# must recover from arbitrary position, not assume it's still nearby.
		_cruise_toward(actor, station_pos, null, 700.0)
		return CONTINUE

	var zone: Dictionary = station.get_port_zone() if station.has_method("get_port_zone") else {}
	if not zone.is_empty():
		if actor.get("docking_grant") == null:
			station.issue_docking_grant(actor) # null (no berths) -- retry next tick
		if actor.get("docking_grant") != null:
			actor.wants_dock = true
	else:
		actor.wants_dock = true

	var berths: Array = station.get_berths() if station.has_method("get_berths") else []
	if berths.is_empty():
		_cruise_toward(actor, station.position, station.position, 700.0)
		return CONTINUE

	var target_berth = berths[0]
	var grant = actor.get("docking_grant")
	if grant != null and grant.get("slip_id", "") != "":
		for b in berths:
			if b.slip_id == grant.get("slip_id", ""):
				target_berth = b
				break

	# FLY THE CORRIDOR (2026-07-26). Previously this aimed at a single point
	# ~0.8 x capture_radius off the berth and passed station.position as
	# `exclude_pos` -- the body steering will NEVER dodge -- from any range and
	# any angle. So a docking ship flew one straight line at the station with
	# station-avoidance switched off for the whole trip.
	#
	# PortChannel already computes the corridor the nav panel draws, and until
	# now nothing outside the renderer read it. Two waypoints come straight out
	# of guide_segment(): the MOUTH (where the berth's approach axis crosses
	# the exclusion boundary) and the ENGAGE point (one capture_radius out from
	# the berth, where the clamp's own reach takes over). Fly mouth -> engage
	# instead of cutting the corner.
	var docking_point: Vector2 = target_berth.global_position
	var berth_heading: float = target_berth.global_rotation
	var boundary_r: float = zone.get("exclusion_radius", 0.0)
	var guide: Dictionary = PortChannel.guide_segment(
		docking_point, berth_heading, station.position, boundary_r, target_berth.capture_radius)

	# Fallback: no authored/derived exclusion zone (ladder levels 0-2 -- mobile
	# homes, open berths) means no corridor to fly. Approach discipline still
	# applies, so aim down the berth's own axis and keep avoiding the hull --
	# see design_ideas/port_zones_and_channels.md on approach discipline being
	# self-imposed and universal, while the published corridor is jurisdiction.
	if guide.is_empty():
		var outward: Vector2 = Vector2.RIGHT.rotated(berth_heading)
		# Same ANGULAR rule as the zoned path, derived from the berth alone --
		# "degrade down the ladder, don't branch". The first version gated on
		# DISTANCE (within capture_radius of the seat) and that was the bug
		# behind the solo-shuttle regression: a couple of hundred units is
		# inside the station's own avoidance standoff, so the hull was repelled
		# right up until a threshold repulsion prevented it reaching. Traffic
		# scenarios hid it because other ships jostle a hull into the seat; a
		# lone shuttle just spiralled (3 cycles / 600s against 4 / 223s).
		# Alignment AND proximity. Angular alone was measured releasing
		# avoidance from ARBITRARY range: in the rock-field scenario a hull far
		# out but roughly on-axis had the station excluded, dodged a rock, and
		# drifted into it -- damage went 0.00% -> 1.00%, worse than baseline.
		# Same error as widening the cone: let go too early and alignment stops
		# meaning anything.
		#
		# The proximity bound DERIVES the exclusion radius this station never
		# authored (PortZone's own rule, hull bounding radius x 6), so the
		# unzoned path is the same rule as the zoned one rather than a second
		# invented threshold -- "degrade down the ladder, don't branch".
		# UNZONED STATIONS KEEP BASELINE BEHAVIOUR: the station stays excluded
		# from avoidance for the whole approach. The cut-out ships only on the
		# ZONED path, where it is measured.
		#
		# Three gates were tried here and all three failed, which is why this
		# is now deliberately conservative:
		#   - distance to the seat  -> a couple of hundred units, inside the
		#     avoidance standoff, so a lone shuttle spiralled (3 cycles/600s).
		#   - angular only          -> released at arbitrary range; a hull
		#     dodging a rock drifted in (rock field 0.00% -> 1.00%).
		#   - angular + derived zone -> the gate condition sits at or inside
		#     the avoidance standoff (Steering.MARGIN 400 plus both radii puts
		#     it ~1550 at a SmallStation), so hulls park at the standoff and
		#     orbit, never aligning. test_nav_gauntlet caught this at Deepcut
		#     (stuck at 1550) and Slag Bay, and test_visitor_itinerary never
		#     reached capture at all.
		#
		# The underlying issue is that goal attraction and obstacle repulsion
		# reach equilibrium at the standoff, and alignment then only happens by
		# luck. A corridor gate cannot fix that on its own -- what the unzoned
		# case actually needs is an approach fix OUTSIDE the standoff, which is
		# the same hold-point geometry the interlock is waiting on.
		# LINE-OF-SIGHT GUIDANCE ONTO THE BERTH AXIS. The unzoned approach is a
		# PATH-FOLLOWING problem, not a waypoint-capture one, and every attempt
		# here up to now solved the wrong one.
		#
		# The immediately preceding attempt (an approach fix at 2x the avoidance
		# standoff, plus a latch on arrival) got closest and still limit-cycled:
		# test_nav_gauntlet's distance-to-station traced 1315 -> 3816 -> 895 ->
		# 3981 -> 1060 -> 5762 at Deepcut, x pinned near the axis while y swung
		# +/-4000 with GROWING amplitude. That is the textbook failure of
		# capture-radius waypoint seeking by a constant-speed, bounded-turn-rate
		# mover: _cruise_toward always commands full speed at its target, so the
		# turn radius at 700 u/s far exceeds the capture tolerance -- the hull
		# sails through, swings back, and the oscillation diverges. No latch can
		# fix that, because the hull never satisfies the arrival test at all.
		#
		# The literature's answer (Lekkas & Fossen's lookahead LOS law -- see
		# design_ideas/approach_guidance_and_avoidance.md) is to steer at a
		# carrot sliding along the PATH instead of at a fixed point: project the
		# hull onto the axis, then aim one lookahead further down it. Cross-track
		# error decays exponentially with distance run -- e(s) = e0 *
		# exp(-s / LOOKAHEAD) -- with no waypoint to overshoot and no arrival
		# condition to satisfy. Lookahead trades convergence rate against
		# overshoot, and the standoff is the natural length scale here (it is
		# both the repulsion radius and roughly the hull's turn radius at
		# cruise), so one standoff of lookahead converges within a few standoffs
		# of run and cannot ring.
		var standoff: float = actor.get_bounding_radius() + station.get_bounding_radius() + Steering.MARGIN
		var rel: Vector2 = actor.position - docking_point
		var along: float = rel.dot(outward)
		var cross_track: float = (rel - outward * along).length()
		var axis_along: float = target_berth.capture_radius * 0.8

		if along <= axis_along:
			# Behind the berth, or already inside the aim point without having
			# captured: no legal run exists from here, so rejoin the axis out in
			# free space -- station AVOIDED, since getting around the hull is
			# precisely what avoidance is for.
			# Braked toward the rejoin point, NOT flown at full cruise. Full cruise
			# was tried on the theory that braking to a stop in empty space is a
			# wasted burn on a heat-limited hull; measured, it is worse on both
			# counts -- the hull sails past the rejoin point and has to come back,
			# so the cycle went from frame 2585 to 3419 and the reactor pegged at
			# max heat anyway. The overshoot costs more thrust than the braking
			# saves.
			var rejoin: Vector2 = docking_point + outward * (standoff * 2.0)
			_cruise_toward(actor, rejoin, null, minf(700.0, Steering.speed_for_arrival(
				actor, actor.position.distance_to(rejoin), Steering.DOCK_APPROACH_SPEED)))
			return CONTINUE

		# THE EXCLUSION GATE IS CROSS-TRACK, NOT ANGULAR. An angular gate was
		# tried and measured worse (rock field 0.00% -> 1.00%) because a fixed
		# angle is a tolerance that GROWS with range: it released avoidance from
		# arbitrary distance, and a hull that then dodged a rock drifted into the
		# body it had stopped watching. Cross-track error is absolute -- the same
		# metres of misalignment mean the same thing at 500 units and at 5000.
		# Once the hull is genuinely on the axis in the outward hemisphere the
		# straight run in is safe by construction (port_channel.gd's geometry:
		# below 90 degrees off-axis the nearest point of the run is the seat
		# itself, which berth_pos_for_bounding_radius already seats outside the
		# hull), and approach_speed_limit independently holds closing speed under
		# COLLISION_DAMAGE_MIN_SPEED. If a dodge does knock the hull off the
		# line, cross-track grows and avoidance comes straight back on -- the
		# self-correction the angular gate could not offer. Hysteresis on the
		# boundary, same shape as the zoned corridor gate, so a hull riding the
		# tolerance does not flip every frame.
		var on_axis: bool = scratch.get("on_axis", false)
		var tol: float = target_berth.capture_radius * (2.0 if on_axis else 1.0)
		on_axis = cross_track <= tol
		scratch["on_axis"] = on_axis
		step["scratch"] = scratch

		# SPEED IS PART OF THE GUIDANCE LAW, but ONLY WHILE THERE IS CROSS-TRACK
		# LEFT TO KILL. The first LOS attempt braked the whole run in and that is
		# what broke test_visitor_itinerary: braking for convergence on top of
		# approach_speed_limit's braking for CONTACT is two brakes for one
		# problem, and it made the cycle 5.3s slower (dock at frame 2535 vs
		# 2216). On this hull that is fatal rather than merely slow -- a
		# CargoShuttle accrues heat at a flat ~2.66/s with no equilibrium, so it
		# reached the berth at 129/150 instead of 111/150 and the exit burn then
		# cooked its reactor (see TASKS.md; the thermal envelope is a separate
		# defect this exposed, not one this code should paper over).
		#
		# A hull already ON the axis does not need to be slow: there is nothing
		# left to steer around, the straight run is geometrically safe, and
		# approach_speed_limit still governs the speed it actually touches the
		# berth at. Braking is for CONVERGENCE, so spend it only while
		# converging.
		#
		# Brake toward the CAPTURE BOUNDARY, not the seat. Inside the capture
		# radius the bay's critically-damped servo owns the hull and arrests it
		# for free (docking_bay.gd); engine-braking through that last stretch
		# pays heat to fight a spring that was going to stop us anyway, and it is
		# the most expensive stretch there is -- lowest speed, longest duration,
		# engine lit the whole way.
		var cruise: float = 700.0
		if not on_axis:
			cruise = minf(700.0, Steering.speed_for_arrival(
				actor, along - target_berth.capture_radius, Steering.DOCK_APPROACH_SPEED))

		# Lookahead scales with commanded speed, floored at the standoff. This is
		# Lekkas & Fossen's time-varying lookahead: a fixed distance is either
		# too tight when fast (overshoot, the failure above) or needlessly slow
		# to converge when crawling. Expressed as a TIME it is one constant that
		# stays correct across a 700 u/s shuttle and a loaded freighter, and it
		# tightens automatically as the braking curve sheds speed.
		var lookahead: float = maxf(standoff, cruise * LOS_LOOKAHEAD_TIME)

		# The carrot: our own projection on the axis, one lookahead nearer the
		# seat, never past the aim point.
		var aim: Vector2 = docking_point + outward * maxf(along - lookahead, axis_along)

		_cruise_toward(actor, aim, station.position if on_axis else null, cruise)
		return CONTINUE

	var mouth: Vector2 = guide["mouth"]
	var engage: Vector2 = guide["engage"]

	# THE CUT-OUT, expressed at the caller rather than inside Steering. The
	# station is only excluded from avoidance once we are actually inside the
	# approach cone; everywhere else it is an ordinary obstacle that pushes
	# back. This is the fix for the measured failure -- an arriving ship that
	# dodges other traffic gets displaced toward the hull, and with a blanket
	# exclusion nothing corrects it.
	#
	# Deciding it here needs no change to Steering's signature or its other
	# call sites: the corridor geometry lives with the caller that knows the
	# berth, and `exclude_pos = null` simply means "avoid normally".
	# HYSTERESIS, not a bare angular test. A ship sitting near the cone edge
	# would otherwise flip between an OUTWARD target (the mouth) and an INWARD
	# one every frame and dither in place -- measured as slower cycles across
	# the board and a Freighter that never berthed at all. Once committed to
	# the corridor it takes a wider angle to fall back out, the same shape
	# RoutePlanner.HYSTERESIS_MARGIN uses against route thrash.
	var axis_theta: float = PortChannel.axis_angle(docking_point, berth_heading, station.position, boundary_r)
	var committed: bool = scratch.get("in_corridor", false)
	if not is_nan(axis_theta):
		var bearing: float = (actor.position - station.position).angle()
		var off_axis: float = absf(wrapf(bearing - axis_theta, -PI, PI))
		var enter: float = PortChannel.CONE_HALF_ANGLE * 0.8
		var leave: float = PortChannel.CONE_HALF_ANGLE * 1.15
		committed = off_axis <= (leave if committed else enter)
		scratch["in_corridor"] = committed
		step["scratch"] = scratch

	# Inside the corridor, fly to the SEAT -- not to `engage`. guide_segment's
	# engage point is where the DRAWN guide stops because the clamp's reach
	# begins, so it sits ON the capture boundary. Steering to it parks the hull
	# at the edge of the capture zone where the clamp never quite takes: light
	# shuttles jittered in eventually, the 300-mass Freighter sat there for the
	# full 600s and logged zero cycles. The seat is inside the clamp's reach,
	# which is what the pre-corridor code aimed at and got right.
	#
	# `engage` still does useful work as the corridor's inner reference; it is
	# just not a destination.
	var seat: Vector2 = docking_point + Vector2.RIGHT.rotated(berth_heading) * (target_berth.capture_radius * 0.8)

	# ALWAYS steer at the seat; `committed` only decides whether the station is
	# avoided on the way. Measured 2026-07-26, and it overturned the obvious
	# design:
	#
	# An earlier version steered at the corridor MOUTH until committed, then at
	# the seat. Damage went to zero -- but the mouth sits ON the boundary
	# circle, so a hull approaching from an arbitrary bearing reaches it
	# TANGENTIALLY while station-avoidance is simultaneously pushing it off. It
	# arcs around the boundary instead of lining up. Cycle time tripled with a
	# SINGLE ship and no traffic (55s -> 180s), MediumStation fell 30 -> 17
	# cycles, and the Freighter circled for the full 600s without ever berthing.
	# Aiming at a point on a circle you are also being repelled from is a bad
	# construction.
	#
	# Steering at the seat with avoidance ON produces the arc for free: the ship
	# heads for the berth, the hull pushes it around, and it enters the cone
	# aligned. Then the cut-out lets it close. The corridor still does the work
	# that matters -- it decides WHEN the station stops being an obstacle -- it
	# just is not a waypoint.
	_cruise_toward(actor, seat, station.position if committed else null, 700.0)
	return CONTINUE

static func _find_station_near(actor, pos: Vector2):
	var tree = actor.get_tree()
	if tree == null:
		return null
	var best = null
	var best_d: float = DOCK_STATION_SEARCH_RADIUS
	for s in tree.get_nodes_in_group("ships"):
		if s == actor:
			continue
		if not s.has_method("get_berths"):
			continue
		if s.get_berths().is_empty():
			continue
		var d: float = s.position.distance_to(pos)
		if d <= best_d:
			best = s
			best_d = d
	return best

# ---------------------------------------------------------------------------
# EXIT_AT {pos, radius=1500.0} -- GO_TO, then despawn.
# ---------------------------------------------------------------------------

static func step_exit_at(actor, step: Dictionary, _job: Dictionary) -> int:
	var pos: Vector2 = step.get("pos", actor.position)
	var radius: float = step.get("radius", 1500.0)
	if actor.position.distance_to(pos) < radius:
		actor.queue_free()
		return DONE
	_cruise_toward(actor, pos, null, step.get("cruise", 700.0))
	return CONTINUE

# ---------------------------------------------------------------------------
# SELECT_VICTIM {lane_pos, lurk_radius=2500.0, witness_range} -- pirate-only.
# Loiters near the lane; scores fresh vessel contacts every ~30 ticks. DONE
# stamps job["victim_iid"].
# ---------------------------------------------------------------------------

static func step_select_victim(actor, step: Dictionary, job: Dictionary) -> int:
	var lane_pos: Vector2 = step.get("lane_pos", actor.position)
	var lurk_radius: float = step.get("lurk_radius", 2500.0)
	var witness_range: float = step.get("witness_range", 5000.0)
	var scratch: Dictionary = step.get("scratch", {})

	# M52a withdraw budget -- two ceilings, whichever trips first:
	#   * attempts: each ENTRY to the hunt (scratch is cleared on entry, so a
	#     fresh scratch is a new victim-engagement cycle re-entered from a
	#     failed INTERCEPT/DEMAND/TAKE) counts one. Bounds a pirate that keeps
	#     FINDING prey but can't land a take (the campaign thrash).
	#   * time: a wall (frame) deadline set on the FIRST hunt entry. Bounds a
	#     pirate that finds NO prey at all and would otherwise lurk forever
	#     (never re-entering, so the attempt counter never advances) -- the
	#     lone-pirate-on-a-long-lane case the viability sim exposed.
	# Either exhausted -> abort to "exit": withdraw alive (-> RETURNED_EMPTY).
	var max_hunt_seconds: float = step.get("max_hunt_seconds", 0.0)
	if max_hunt_seconds > 0.0:
		if not job.has("hunt_deadline_frame"):
			job["hunt_deadline_frame"] = Engine.get_physics_frames() + int(max_hunt_seconds * PHYSICS_HZ)
		if Engine.get_physics_frames() > job["hunt_deadline_frame"]:
			job["_abort_reason"] = "hunt time budget (%.0fs) spent, no take -- withdrawing" % max_hunt_seconds
			return ABORT
	if not scratch.get("counted", false):
		scratch["counted"] = true
		job["hunt_attempts"] = job.get("hunt_attempts", 0) + 1
		var max_attempts: int = step.get("max_attempts", 0)
		if max_attempts > 0 and job["hunt_attempts"] > max_attempts:
			job["_abort_reason"] = "hunt budget spent (%d attempts, nothing taken) -- withdrawing" % (job["hunt_attempts"] - 1)
			return ABORT

	var to_lane: Vector2 = lane_pos - actor.position
	if to_lane.length() > lurk_radius:
		_cruise_toward(actor, lane_pos, null, 300.0)
	else:
		_hold_station(actor)

	var frame := Engine.get_physics_frames()
	var last_scan: int = scratch.get("last_scan_frame", -SELECT_VICTIM_SCAN_INTERVAL)
	if frame - last_scan < SELECT_VICTIM_SCAN_INTERVAL:
		return CONTINUE
	scratch["last_scan_frame"] = frame

	# Every fresh vessel contact (any standing) -- used for the ALONE check;
	# a witness is a witness regardless of what we've judged it.
	var all_fresh_vessels: Array = []
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if not _is_fresh(actor, c):
			continue
		if not Standing.is_vessel(c.get("classification", "")):
			continue
		all_fresh_vessels.append(c)

	# Viable prey: NEUTRAL or CAUTION (never FRIENDLY-crypto, never
	# HOSTILE), and not currently complied (already someone else's mark --
	# the one ship-knowable proxy for "already being robbed/inspected").
	# M52a failure memory: skip a victim we recently failed on (job[
	# "failed_victims"][iid] holds a cooldown expiry frame) -- a ship we
	# already demanded is alerted and running, so re-picking it is the thrash
	# the campaign showed. Give it a rest and look for fresh prey.
	var blacklist: Dictionary = job.get("failed_victims", {})
	var now_frame := Engine.get_physics_frames()
	var candidates: Array = []
	for c in all_fresh_vessels:
		var standing: String = c.get("standing", "")
		if standing != Standing.NEUTRAL and standing != Standing.CAUTION:
			continue
		if c.get("complied_stop", false):
			continue
		if blacklist.get(c.get("instance_id", -1), 0) > now_frame:
			continue
		candidates.append(c)

	var viable: Array = []
	for c in candidates:
		var alone := true
		for other in all_fresh_vessels:
			if other == c:
				continue
			if c.get("pos", Vector2.ZERO).distance_to(other.get("pos", Vector2.ZERO)) <= witness_range:
				alone = false
				break
		if alone:
			viable.append(c)

	if viable.is_empty():
		return CONTINUE

	var best = viable[0]
	var best_cs: float = best.get("signature", {}).get("cross_section", INF)
	for c in viable:
		var cs: float = c.get("signature", {}).get("cross_section", INF)
		if cs < best_cs:
			best_cs = cs
			best = c

	job["victim_iid"] = best.get("instance_id", -1)
	return DONE

# ---------------------------------------------------------------------------
# INTERCEPT {standoff=400.0, cruise=600.0} -- revised (calling session,
# 2026-07-23): DONE once within hailing range of job["victim_iid"]'s track,
# full stop -- no speed-match requirement anymore. The old gate (ALSO
# requiring relative speed under INTERCEPT_SPEED_MATCH_THRESHOLD) forced the
# approach to already be basically at boarding position AND velocity-matched
# before DEMAND_STOP's hail/show-colors ever fired -- playtest read that as
# "they were trying to board me before the hail even showed up." Now the
# demand (and showing colors) goes out from communication range, well
# outside boarding distance; DEMAND_STOP's own pacing (_pace_at_offset, the
# same safe standoff approach this step still uses on its way there) does
# the actual closing-in AFTER the hail is already out -- "hail from farther
# away, fly colors, THEN get into position," not the reverse. The standoff-
# offset target point (never the victim's own position) still keeps this
# leg from ever aiming through the victim's hull even while covering that
# ground. ABORT if the track's gone stale (belt to the runner's own victim_
# lost abort_when, same "suspenders" idiom fire_opportunity_leaf uses
# alongside fire_weapon's own guard).
# ---------------------------------------------------------------------------

static func step_intercept(actor, step: Dictionary, job: Dictionary) -> int:
	var victim_iid: int = job.get("victim_iid", -1)
	var c: Dictionary = _contact_for_instance(actor, victim_iid)
	if not _is_fresh(actor, c):
		job["_abort_reason"] = "victim track lost"
		return ABORT

	var scratch: Dictionary = step.get("scratch", {})
	var victim_pos: Vector2 = c.get("pos", actor.position)
	var victim_vel: Vector2 = c.get("vel", Vector2.ZERO)
	var standoff_dist: float = step.get("standoff", INTERCEPT_STANDOFF_DIST)

	var hail_range: float = _hail_range_to(actor, victim_iid)
	var dist: float = actor.position.distance_to(victim_pos)
	var close_enough: bool = (hail_range > 0.0 and dist <= hail_range) or dist <= standoff_dist * 1.25
	if close_enough:
		return DONE

	var offset: Vector2 = _standoff_offset(actor, victim_pos, victim_vel, standoff_dist, scratch)
	_pace_at_offset(actor, victim_pos + offset, victim_vel, victim_pos, step.get("cruise", 600.0))
	return CONTINUE

# ---------------------------------------------------------------------------
# DEMAND_STOP {show_colors=false, patience=25.0, standoff=400.0} -- send
# DEMAND(STOP), then heartbeat-refresh it (M52d); DONE when our own track on
# the victim shows complied_stop (M49 stamps this on ACKNOWLEDGE receipt);
# ABORT when outpaced beyond hail range or patience expires un-complied.
#
# M52c: movement PACES the victim at the standoff offset (_pace_at_offset)
# instead of chasing its raw position (_cruise_toward) -- this was the
# playtest's ram: a moving victim's raw position is a pursuit curve that
# terminates in its hull. A victim that complies decelerates, so the pace
# naturally settles into a stationary alongside as its velocity drops; a
# victim that runs opens the gap and the outpaced/patience aborts below fire
# unchanged.
# ---------------------------------------------------------------------------

static func step_demand_stop(actor, step: Dictionary, job: Dictionary) -> int:
	var victim_iid: int = job.get("victim_iid", -1)
	var scratch: Dictionary = step.get("scratch", {})

	# HOISTING COLOURS IS NOW A CHOICE, NOT A REFLEX (2026-08-01).
	#
	# show_colors used to fire unconditionally, which made every robbery a
	# public declaration: FLAG_PIRATE is in everyone's default
	# known_enemy_flags, so the instant it goes up the pirate is HOSTILE to
	# every hull in transponder range and the only enforcement path that can
	# touch it swings open. `colors_chance` lets a pirate run the demand under
	# its cover identity instead -- quieter, but the victim is being leaned on
	# by an apparent civilian rather than by an obvious pirate.
	#
	# Rolled ONCE per demand and remembered, not re-rolled per tick: the step
	# runs every frame and a per-tick roll would flicker the transponder,
	# which is both nonsense and a datalink storm.
	if not scratch.has("colors_decided"):
		scratch["colors_decided"] = step.get("show_colors", false) \
			and randf() < step.get("colors_chance", 1.0)
	if scratch["colors_decided"] and not scratch.get("colors_shown", false):
		actor.set_transponder_flag(Standing.FLAG_PIRATE)
		actor.set_transponder_active(true)
		scratch["colors_shown"] = true

	var c: Dictionary = _contact_for_instance(actor, victim_iid)
	if c.is_empty():
		job["_abort_reason"] = "victim track lost"
		return ABORT

	# REPRISAL FOR CALLING FOR HELP (2026-08-01).
	#
	# Until now an SOS was free: the victim broadcast, and the pirate neither
	# knew nor cared. This gives the call a price, so a hauler's decision to
	# shout is a gamble rather than an obvious yes.
	#
	# Expressed as a punitive shot rather than a switch to combat AI because a
	# pirate has NO Engage leaf -- build_pirate is Disengage -> JobRunner ->
	# Idle, so everything a pirate does must happen inside a job step. The hull
	# carries one light laser; this is it being used.
	#
	# Rolled ONCE per demand. The victim posts its own ASSAULT warrant off the
	# hit (take_damage's own-hit path), so the consequence propagates through
	# the normal standing machinery rather than needing special casing.
	var reprisal_chance: float = step.get("sos_reprisal_chance", 0.0)
	if reprisal_chance > 0.0 and not scratch.has("reprisal_rolled") and c.get("sos", false):
		scratch["reprisal_rolled"] = true
		if randf() < reprisal_chance:
			var vict = instance_from_id(victim_iid)
			if vict != null and is_instance_valid(vict) and vict.has_method("take_damage"):
				if DebugSettings and DebugSettings.get_choice("job_log") == DebugSettings.JobLog.ON:
					print("[Job] %s: REPRISAL -- victim called for help, firing" % actor.debug_label())
				vict.take_damage(step.get("reprisal_damage", 40.0),
					vict.position, (vict.position - actor.position).normalized(),
					"laser", actor.get_instance_id())

	if c.get("complied_stop", false):
		return DONE

	var victim_pos_demand: Vector2 = c.get("pos", actor.position)
	var victim_vel_demand: Vector2 = c.get("vel", Vector2.ZERO)
	var standoff_dist: float = step.get("standoff", INTERCEPT_STANDOFF_DIST)
	var offset: Vector2 = _standoff_offset(actor, victim_pos_demand, victim_vel_demand, standoff_dist, scratch)
	_pace_at_offset(actor, victim_pos_demand + offset, victim_vel_demand, victim_pos_demand, step.get("cruise", 400.0))

	# M52d -- heartbeat: first pass ISSUES the demand (new seq), every ~2s
	# after that RE-ASSERTS it under the same seq so the victim's pending_
	# demand stays alive exactly as long as this step keeps running. The seq
	# is ALSO stashed on the job dict (not just this step's own scratch,
	# which resets on entry to a DIFFERENT step) -- TAKE_ALONGSIDE needs the
	# same seq to keep refreshing the HOLD once the victim has complied.
	# Abort/DONE simply stops the refreshes; no explicit "end the demand"
	# send is needed on any path -- the RELEASE verb doesn't exist under the
	# channel model, the victim's own heartbeat timeout is the only cleanup.
	var frame_now := Engine.get_physics_frames()
	if not scratch.get("demand_sent", false):
		var seq: int = actor.send_demand(victim_iid, Hail.RUNG_STOP)
		scratch["demand_seq"] = seq
		scratch["demand_sent"] = true
		scratch["last_refresh_frame"] = frame_now
		job["demand_seq"] = seq
	elif frame_now - scratch.get("last_refresh_frame", 0) >= DEMAND_REFRESH_FRAMES:
		actor.refresh_demand(victim_iid, Hail.RUNG_STOP, scratch.get("demand_seq", -1))
		scratch["last_refresh_frame"] = frame_now

	var patience: float = step.get("patience", 25.0)
	if _elapsed_seconds(scratch, "start_frame") > patience:
		job["_abort_reason"] = "patience %.0fs expired un-complied" % patience
		_blacklist_victim(job, victim_iid)
		return ABORT

	var hail_range: float = _hail_range_to(actor, victim_iid)
	var dist: float = actor.position.distance_to(c.get("pos", actor.position))
	if hail_range > 0.0 and dist > hail_range * 1.2:
		job["_abort_reason"] = "victim outpaced us beyond hail range (%.0f > %.0f)" % [dist, hail_range]
		_blacklist_victim(job, victim_iid)
		return ABORT # outpacing us beyond hail range -- let it go

	return CONTINUE

# ---------------------------------------------------------------------------
# TAKE_ALONGSIDE {hold_time=12.0, range=200.0} -- M52c robbery theater
# (soft-dock): formation-lock at `range` -- actor _pace_at_offset's to the
# victim's own offset point and zeroes RELATIVE velocity, the same "hold
# rigidly" idiom _hold_station used for a stationary target, extended to
# hold a moving offset (a victim whose complied_stop still carries a little
# residual drift is paced, not out-braked out of formation). Accumulate
# hold_time ONLY while inside `range` and still complied -- drifting out
# pauses the clock (below), same as before M52c. DONE: loot_takes += 1,
# victim.looted = true. ABORT if complied_stop clears (victim bolted).
# `range` doubles as the soft-dock's standoff distance (see _standoff_
# offset) -- tightened from the old 600u "nearby" to something that reads as
# genuinely alongside, not the wider flanking distance INTERCEPT/DEMAND_STOP
# hold at.
#
# M52d -- keeps refreshing job["demand_seq"] (stashed by DEMAND_STOP) the
# WHOLE time this step runs: compelled_stop on the victim is heartbeat-kept
# exactly like pending_demand (design revised in review, RELEASE removed),
# so without a refresh here the hold would lapse mid-robbery on its own
# timeout. The refresh keeps going even while out of range/re-closing
# (below) -- the pirate still wants the hold, it just hasn't caught up yet.
#
# M52c -- the in-range check carries hysteresis (TAKE_ALONGSIDE_EXIT_SLACK):
# a hold already in progress only pauses past range*1.25, not the instant
# distance ticks over `range` itself. A throwaway debug trace at the
# tightened 200u default caught the pirate genuinely holding formation
# (position noise + control-loop response bouncing a few tens of units,
# +-15-20u, around the boundary) but dist crossing back and forth over the
# bare `range` cutoff every tick, erasing hold_start_frame each time and
# never accumulating -- a hold that visibly held station never finished. The
# 600u default this replaced never showed it (the same jitter is a much
# smaller fraction of a wider envelope); tightening the envelope is exactly
# what surfaced it.
# ---------------------------------------------------------------------------

static func step_take_alongside(actor, step: Dictionary, job: Dictionary) -> int:
	var victim_iid: int = job.get("victim_iid", -1)
	var scratch: Dictionary = step.get("scratch", {})
	var range: float = step.get("range", 200.0)
	var hold_time: float = step.get("hold_time", 12.0)

	var c: Dictionary = _contact_for_instance(actor, victim_iid)
	if c.is_empty() or not c.get("complied_stop", false):
		job["_abort_reason"] = "victim bolted (complied_stop cleared)"
		_blacklist_victim(job, victim_iid)
		return ABORT

	var frame_now := Engine.get_physics_frames()
	if frame_now - scratch.get("last_refresh_frame", -DEMAND_REFRESH_FRAMES) >= DEMAND_REFRESH_FRAMES:
		actor.refresh_demand(victim_iid, Hail.RUNG_STOP, job.get("demand_seq", -1))
		scratch["last_refresh_frame"] = frame_now

	var victim_pos_take: Vector2 = c.get("pos", actor.position)
	var victim_vel_take: Vector2 = c.get("vel", Vector2.ZERO)
	var offset: Vector2 = _standoff_offset(actor, victim_pos_take, victim_vel_take, range, scratch)
	_pace_at_offset(actor, victim_pos_take + offset, victim_vel_take, victim_pos_take, step.get("cruise", 300.0))

	var dist: float = actor.position.distance_to(victim_pos_take)
	var in_hold: bool = scratch.has("hold_start_frame")
	var within: bool = dist <= (range * TAKE_ALONGSIDE_EXIT_SLACK if in_hold else range)
	if not within:
		scratch.erase("hold_start_frame") # only accumulate while actually in range
		return CONTINUE

	var frame := Engine.get_physics_frames()
	if not scratch.has("hold_start_frame"):
		scratch["hold_start_frame"] = frame
	var held_elapsed: float = (frame - scratch["hold_start_frame"]) / PHYSICS_HZ
	if held_elapsed < hold_time:
		return CONTINUE

	actor.loot_takes += 1
	var victim = instance_from_id(victim_iid)
	if victim != null and is_instance_valid(victim):
		victim.looted = true
		# M52b -- ARMED_ROBBERY warrant, posted into the VICTIM's OWN store
		# (nothing posted this offense before this milestone -- design doc's
		# taxonomy: "pirate job takes loot"). Same "whoever experienced it
		# posts it" shape as take_damage's own-hit ASSAULT post above; the
		# victim names the pirate off whatever it can actually see (its own
		# live track + transponder read on the pirate), the "honesty rule"
		# the design doc's subject field is built around.
		var pirate_trk: String = Ship.track_id(actor.get_instance_id())
		var pirate_c: Dictionary = victim.active_contacts.get(pirate_trk, {})
		var pirate_claimed: String = victim.active_transponders.get(actor.get_instance_id(), {}).get("name", "")
		victim.post_warrant(Standing.OFF_ARMED_ROBBERY, pirate_claimed, pirate_c.get("signature", {}), "took cargo")
		# M57 -- the same event, recorded as EVIDENCE alongside the verdict.
		# The warrant above answers "is this hull wanted" and OVERWRITES on the
		# next offense by the same pirate; this answers "what happened, WHERE"
		# and never does. A patrol cannot plan a route from the warrant (no
		# position, and one record per (offense, subject) no matter how many
		# times it happens) -- it can from these.
		#
		# Deliberately reusing the honest values computed just above rather than
		# reading the pirate node: `pirate_claimed` is the victim's transponder
		# read, so an undercover pirate is recorded under its COVER name, and a
		# dark one as "". An incident naming the real hull would be the director
		# cheating through a witness. Position is the VICTIM's own -- it is the
		# reporter, and it knows where it is.
		if victim.has_method("record_incident"):
			var pirate_flag: String = victim.active_transponders.get(actor.get_instance_id(), {}).get("flag", "")
			# The same signature the warrant above was keyed on, carried as
			# EVIDENCE (a patrol director correlating sightings wants it), not
			# as an identity. It does NOT make the record survive a rename:
			# Standing.subject_key returns "name:<claimed>" whenever a name is
			# present and never consults the signature, so a rename produces a
			# new key regardless. See Ship.notarize_from for why a
			# signature-only report is refused outright.
			victim.record_incident(Incident.KIND_ARMED_ROBBERY, pirate_claimed, pirate_flag,
				victim.position, "", pirate_c.get("signature", {}))
		# Eager same-tick cache stamp (ship.gd's take_damage carries the full
		# rationale): compute_standing only re-runs on this track's next
		# sensor-bin update, not every physics tick, so without this the
		# victim's own read on the pirate wouldn't flip until that next
		# sweep. No-op if the victim holds no live track on the pirate.
		if not pirate_c.is_empty():
			pirate_c["standing"] = Standing.HOSTILE
			pirate_c["standing_reason"] = "took cargo"
	# M52d -- no RELEASE send: the step simply stops running (and therefore
	# stops refreshing), and the victim's own compelled_stop heartbeat
	# timeout ends the hold a few seconds later. Same latency trade as the
	# demand side -- "the fiction working FOR us" per the design doc.
	return DONE

# ---------------------------------------------------------------------------
# Abort condition helpers (shared, runner-evaluated).
# ---------------------------------------------------------------------------

# Any fresh UNIDENTIFIED VESSEL track that is neither the victim nor
# FRIENDLY, within r of ME. Per the design doc: "this is the pirate's own
# witness/patrol-closing read -- it cannot know a contact's ROLE, a witness
# is a witness."
static func _third_party_in_range(actor, job: Dictionary, r: float) -> bool:
	var victim_iid: int = job.get("victim_iid", -1)
	for c_id in actor.active_contacts:
		var c: Dictionary = actor.active_contacts[c_id]
		if not _is_fresh(actor, c):
			continue
		if c.get("classification", "") != "UNIDENTIFIED VESSEL":
			continue
		if c.get("instance_id", -1) == victim_iid:
			continue
		var d: float = actor.position.distance_to(c.get("pos", actor.position))
		if d <= r:
			# M52a: stamp WHO tripped the witness check so the abort log can
			# name it -- track id + range (the campaign log showed a bare
			# "third_party_in_range" with no way to tell a beacon from a patrol).
			job["_abort_reason"] = "witness %s at %.0f" % [c_id, d]
			return true
	return false

static func _victim_lost(actor, job: Dictionary) -> bool:
	var victim_iid: int = job.get("victim_iid", -1)
	if victim_iid == -1:
		return true
	return not _is_fresh(actor, _contact_for_instance(actor, victim_iid))
