class_name UIStyle

# The console's shared visual vocabulary. See
# design_ideas/2026-07-27-ui_style_guide.md for the audit this came from and
# the reasoning behind each rule -- this file is the enforcement, that file is
# the argument.
#
# Reference via the preload-const convention (CLAUDE.md -- the git-tracked
# global class cache isn't regenerated by the headless --run-test path):
#   const UIStyle = preload("res://scripts/ui/ui_style.gd")
#
const Utils = preload("res://scripts/utils.gd")

# The rule of thumb for adding to this file: put it here if two panels would
# otherwise each spell it out. Do NOT put semantic colour here -- a contact's
# colour encodes its standing and lives in Utils.contact_color, which
# deliberately OVERRIDES panel accent (playtest A2). This module owns chrome;
# Utils owns meaning.

# --- Font ramp ---------------------------------------------------------------
# Six values, down from eight ad-hoc ones (11/12/13/14/15/16/20/28, three of
# them used once each). TITLE and READOUT are both the same size on purpose and
# stay separately named: they answer different questions and may diverge.
#
# 2026-07-27: the whole ramp moved +2 (the console was too small to read at a
# glance). It moved TOGETHER with project.godot's gui/theme/default_font_size,
# which governs every label with no explicit override -- most of them. Bump one
# without the other and the scale re-splits into two.
const FONT_DETAIL := 14   # list detail lines, log text, secondary readouts
const FONT_BODY := 15     # section headers, default prose
const FONT_TITLE := 18    # panel titles
const FONT_READOUT := 18  # numerals read at a glance (helm gauges)
const FONT_BANNER := 22   # transient full-width banners (zone crossing)
const FONT_ALERT := 30    # the overheat warning -- an interrupt, not content

# Canvas text (draw_string on a map, dial, chart or sensor scope) is its own
# family and legitimately runs smaller than UI chrome: it overlays graphics,
# and there can be dozens of labels competing for the same pixels. Same +2
# treatment, and the five ad-hoc values it had (9/10/12/14/16) collapse to
# four -- 9 and 10 were a distinction nobody could see.
const FONT_CANVAS_TINY := 12   # chart legends, sensor bin labels, per-contact detail lines
const FONT_CANVAS_SMALL := 14  # map contact labels, contract markers
const FONT_CANVAS := 16        # compass ticks, scale bar, speed numeral
const FONT_CANVAS_LARGE := 18  # world-coordinate readout, sensor module title

# --- Panel accents -----------------------------------------------------------
# ONE colour per panel, driving BOTH the frame border (terminal_display) and
# the panel title. These were previously two independently-chosen literals per
# panel that had already drifted apart (contacts framed in (0.2,0.4,0.2) but
# titled in pure GREEN, engineering framed in (0.6,0.4,0.1) but titled in
# (0.8,0.6,0.2), and so on).
#
# Hue per panel is deliberate and must NOT be unified away -- it is how a
# player finds a panel on a dense screen before reading a word of it.
const ACCENT_NAV := Color(0.3, 0.7, 0.3)
const ACCENT_CONTACTS := Color(0.3, 0.7, 0.3)
const ACCENT_HELM := Color(0.3, 0.7, 0.3)
const ACCENT_WEAPONS := Color(0.85, 0.25, 0.25)
const ACCENT_ENGINEERING := Color(0.85, 0.65, 0.2)
const ACCENT_COMMS := Color(0.3, 0.75, 0.9)
const ACCENT_SENSORS := Color(0.3, 0.7, 0.3)
# Modal overlays (help, controls remap) are not part of the console and share
# one neutral blue chrome rather than borrowing a panel's identity.
const ACCENT_MODAL := Color(0.3, 0.6, 0.9)

# Frame borders read as a quieter version of the same accent so the title is
# the loud instance of the colour and the border merely echoes it.
const FRAME_BORDER_DIM := 0.55
# Section headers sit a step below their panel title in the same hue.
const SECTION_HEADER_DIM := 0.7

static func dim(c: Color, factor: float) -> Color:
	return Color(c.r * factor, c.g * factor, c.b * factor, c.a)

# --- Headings ----------------------------------------------------------------

# Level 1: names a whole console panel. Exactly one per panel. Callers add the
# separator themselves only if they want one -- see panel_title_with_rule().
static func panel_title(text: String, accent: Color) -> Label:
	var lbl := Label.new()
	lbl.text = text
	lbl.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	lbl.add_theme_font_size_override("font_size", FONT_TITLE)
	lbl.add_theme_color_override("font_color", accent)
	return lbl

# Level 2: a division inside a panel, holding a FIXED readout. A section whose
# content is an unbounded list wants list_section() instead -- folding exists
# so a long list can be gotten out of the way, and a two-line readout has
# nothing to get out of the way.
static func section_header(text: String, accent: Color) -> Label:
	var lbl := Label.new()
	lbl.text = text
	lbl.add_theme_font_size_override("font_size", FONT_BODY)
	lbl.add_theme_color_override("font_color", dim(accent, SECTION_HEADER_DIM))
	return lbl

# Level 3: a section header WITH a fold affordance, for unbounded lists.
# Returns {"button": Button, "content": VBoxContainer} -- the caller parents
# both (button first) and fills content. The button owns the collapse wiring
# and its own "(+)/(-)" suffix, matching what contacts_panel has always done;
# set_list_section_title() updates the label without disturbing that.
static func list_section(text: String, accent: Color, start_collapsed: bool = false) -> Dictionary:
	var btn := Button.new()
	btn.toggle_mode = true
	btn.button_pressed = start_collapsed
	btn.alignment = HORIZONTAL_ALIGNMENT_LEFT
	btn.add_theme_font_size_override("font_size", FONT_BODY)
	btn.add_theme_color_override("font_color", dim(accent, SECTION_HEADER_DIM))

	var content := VBoxContainer.new()
	content.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	content.visible = not start_collapsed

	set_list_section_title(btn, text)
	btn.toggled.connect(func(pressed: bool):
		content.visible = not pressed
		set_list_section_title(btn, btn.get_meta("base_text", text))
	)
	return {"button": btn, "content": content}

# Re-label a list section (e.g. to refresh a live count) while preserving the
# collapse marker. Stores the bare text as metadata so the marker can be
# re-derived rather than parsed back off the label.
static func set_list_section_title(btn: Button, text: String) -> void:
	btn.set_meta("base_text", text)
	btn.text = text + (" (+)" if btn.button_pressed else " (-)")

# --- Rows --------------------------------------------------------------------

# ONE row shape for an entity listed anywhere (tactical contacts, hails).
# A 4px left tab in the entity's own colour, not a box: the tab scales down a
# long list into one gutter of colour, where per-row boxes turn twenty rows
# into a grid of noise. `color` is semantic (Utils.contact_color) and is
# deliberately allowed to clash with the panel accent.
static func row_style(color: Color, selected: bool) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = Utils.ROW_BG_SELECTED if selected else Utils.ROW_BG
	s.border_width_left = 4
	s.border_color = color
	s.set_content_margin_all(4)
	return s

# --- Padding -----------------------------------------------------------------
# Text must not run into the box that contains it. Before this, panel frames
# carried a 3px margin on all four sides -- enough to keep a border off the
# glyphs, not enough to read as an inset -- so free-standing text (the
# engineering log, a ship name) sat flush against the frame while anything
# inside a control with its OWN padding (every CheckButton, e.g. "Broadcast
# Active") appeared correctly indented. Two different left edges in the same
# column, which is what the playtest saw.
#
# Horizontal is the one that matters: it is what a reader's eye aligns
# against. Vertical stays tight -- the console is dense on purpose.
const FRAME_PAD_H := 8
const FRAME_PAD_V := 4
# Nested boxes (the transponder block, the chat pane) sit INSIDE a frame that
# has already paid FRAME_PAD_H, so they add less.
const INNER_PAD := 6

static func _pad(s: StyleBoxFlat, h: int, v: int) -> void:
	s.content_margin_left = h
	s.content_margin_right = h
	s.content_margin_top = v
	s.content_margin_bottom = v

# --- Panel frames ------------------------------------------------------------

# The outer frame terminal_display wraps each panel in. `edges` names which
# sides carry the 2px rule, e.g. ["left"] or ["top", "left"].
static func panel_frame(accent: Color, bg: Color, edges: Array) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = bg
	s.border_color = dim(accent, FRAME_BORDER_DIM)
	for e in edges:
		match e:
			"left": s.border_width_left = 2
			"right": s.border_width_right = 2
			"top": s.border_width_top = 2
			"bottom": s.border_width_bottom = 2
	_pad(s, FRAME_PAD_H, FRAME_PAD_V)
	return s

# A tinted box nested inside a panel (the comms transponder block, the chat
# pane). Same padding contract as a frame, just smaller, so its contents don't
# sit flush against its own fill the way the frame's used to.
static func inner_panel(bg: Color, accent: Color = Color(0, 0, 0, 0), edges: Array = []) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = bg
	if accent.a > 0.0:
		s.border_color = accent
		for e in edges:
			match e:
				"left": s.border_width_left = 2
				"right": s.border_width_right = 2
				"top": s.border_width_top = 2
				"bottom": s.border_width_bottom = 2
	_pad(s, INNER_PAD, INNER_PAD)
	return s

# A modal overlay's frame -- fully bordered and generously padded, the opposite
# of a console panel's single edge rule. help_overlay and controls_menu had
# byte-identical copies of this.
static func modal_frame() -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = Color(0.06, 0.07, 0.09, 0.98)
	s.border_color = ACCENT_MODAL
	s.set_border_width_all(2)
	s.set_content_margin_all(18)
	return s
