extends RigidBody2D
class_name Ship

const WeaponBehaviorRegistry = preload("res://scripts/components/weapon_behavior_registry.gd")
# Referenced via preload const (same pattern as WeaponBehaviorRegistry above)
# rather than the global `ComponentSpec` class_name: the git-tracked global
# class cache isn't regenerated by the headless `--run-test` path, so relying on
# the global name makes ship.gd fail to compile until someone reopens the editor.
# The const resolves regardless of cache state and is inherited by subclasses
# (Frigate uses it for ship_tier). See implementation_plans/m9b_spec_chart_design.md.
const ComponentSpec = preload("res://scripts/components/component_spec.gd")

# Mass is derived from each component's rect area x density, not authored directly.
# Calibrated so the default Frigate loadout (total area 2775 x density 20.0)
# reproduces its original flat mass of 100.0 -- smaller ships built from the
# same density naturally come out lighter.
const MASS_SCALE := 100.0 / 55500.0

# Inertia is likewise derived (point-mass approximation: sum of each component's
# mass x squared distance from ship center). Calibrated so the default Frigate
# loadout's raw sum (~40422.30) reproduces its original flat inertia of 1000.0.
const INERTIA_SCALE := 1000.0 / 40422.2973

# Combat heat from take_damage() decays at this rate (per second) instead of
# being overwritten outright by the per-frame heat/EM dispatch loop below --
# see _decay_damage_heat().
const DAMAGE_HEAT_DECAY_RATE := 20.0

# A damaged engine's EM baseline still drops with health (less power, less
# output -- physically right), but damage also adds a rectified oscillation
# on top so "damaged" reads as running rough, not just quieter. Frequency
# rises with damage but stays under 1Hz even at 100% so it's a player-visible
# pulse rather than aliasing into noise against sensor refresh rates -- see
# _engine_damage_oscillation().
const ENGINE_OSC_FREQ_BASE := 0.2   # Hz, lightly-damaged flicker rate (~5s period)
const ENGINE_OSC_FREQ_RANGE := 0.6  # Hz, added at 100% damage -> max 0.8Hz (~1.25s period)
const ENGINE_OSC_GAIN := 1.0        # crest height relative to power_rating at 100% damage

# A reactor crossing from alive to destroyed fires a one-shot EM "whiteout"
# scaled to its own power_rating (so Missile's tiny capacitor and Frigate's
# full reactor both decay over the same duration, not the same magnitude --
# see _update_reactor_whiteout()).
const REACTOR_WHITEOUT_MULTIPLIER := 5.0 # crest height relative to power_rating
const REACTOR_WHITEOUT_DURATION := 1.5   # seconds to decay to zero

# Flight-control feel constants (_physics_process). Smooth mode (steering_mode
# == 0) deliberately cuts rotational authority harder than linear throttle --
# it's meant to feel like a cruise/precision mode, not just "everything at
# half power" -- so torque and max-omega get their own, smaller ratios rather
# than reusing the throttle one.
const VELOCITY_CONTROL_GAIN := 2.0    # P-gain: required_accel = v_error * this
const SMOOTH_MODE_THRUST_RATIO := 0.5 # Smooth-mode throttle cap vs Combat's full +/-1.0
const SMOOTH_MODE_TORQUE_RATIO := 0.2 # Smooth-mode torque cap vs Combat's full ship_max_torque
const SMOOTH_MODE_OMEGA_RATIO := 0.25 # Smooth-mode max-omega cap vs Combat's full max_omega
const ROTATION_TRACKING_GAIN := 10.0  # required_alpha = omega_error * this -- how aggressively torque tracks the time-optimal turn curve

# Heat-budget constants (_physics_process). max_heat/heat_dissipation_rate
# below are per-ship-class vars (Missile overrides both -- see missile.gd),
# but the formulas that feed them are shared across every ship and live here.
const REACTOR_HEAT_COEFFICIENT := 2.0 # reactor_heat = this * reactor power slider (0-1)
const OVERHEAT_DAMAGE_RATE := 10.0    # HP/sec drained from reactors while current_heat is pegged at max_heat
const PASSIVE_COMPONENT_HEAT := 0.1   # flat heat leak per powered, alive, non-hull component
const PASSIVE_COMPONENT_EM := 0.5     # flat EM leak per powered, alive, non-hull component
const REACTOR_HEAT_FLOOR := 10.0      # a reactor's own resting heat even with no load
const SENSOR_HEAT_FLOOR := 5.0        # an active sensor's own resting heat even with no load
const PASSIVE_HEAT_DISSIPATION_RATE := 2.0 # radiative cooling that applies even with the reactor off/dead -- without it, a hulk's current_heat freezes forever at whatever it was the instant it died, since active dissipation is reactor-pumped

# classify_contact() thresholds. cross-section splits "small" (ordnance-sized)
# from "large" (vessel-sized) contacts; vessels get a higher heat bar than
# ordnance because a cold-running missile/torpedo should still read as a
# threat at a lower heat signature than a cold-running ship would need to.
const ORDNANCE_CS_THRESHOLD := 10.0    # cross_section below this reads as ordnance, not a vessel
const ACTIVE_EM_THRESHOLD := 5.0       # em_noise above this means "powered and active" for any object class
const ORDNANCE_HEAT_THRESHOLD := 5.0   # heat above this flags a small (ordnance-sized) contact as active
const VESSEL_HEAT_THRESHOLD := 10.0    # heat above this flags a large (vessel-sized) contact as active
const ASTEROID_DENSITY_THRESHOLD := 250.0 # denser than this (and big enough) reads as rock, not dead metal
const ASTEROID_CS_THRESHOLD := 50.0    # minimum size to be called an asteroid rather than wreckage debris
const UNKNOWN_DENSITY_DEFAULT := 500.0 # density assumed when a signature omits the field entirely

# Sensor fusion / contact tracking (_physics_process contact decay + correlate-tracks).
const CONTACT_TIMEOUT := 20.0          # seconds with no fresh detection before a tracked contact is dropped
const CONTACT_CORRELATION_RANGE := 2000.0 # max distance (no instance_id match) to fuse a new blip into an existing contact instead of starting a new one
const CONTACT_RESOLUTION_STALE_TIME := 0.3 # seconds since the last position update before a coarser-resolution bin is allowed to override position anyway
const CONTACT_FUSION_SMOOTHING := 0.8  # lerp weight toward each new reading -- shared by pos/vel/cross_section/heat/em_noise so none of them drift out of sync with the others
const PASSIVE_EM_NOISE_FLOOR := 15.0   # received EM (after range/direction falloff) below this is undetectable by passive sensors
const EM_FALLOFF_REFERENCE_DISTANCE := 10000.0 # distance at which received EM starts dropping below the broadcast value
const SENSOR_VELOCITY_NOISE := 0.05    # +/- fractional magnitude and +/- radian jitter applied to a sensor's reported target velocity
const SENSOR_POS_NOISE := 0.005        # +/- fractional distance noise and bin fraction noise applied to reported target position


# take_damage() raymarch / damage-soak constants.
const DAMAGE_RAYMARCH_STEP := 2.0      # px per step along the hit ray when distributing damage across internal components
const MIN_EFFECTIVE_DENSITY := 0.05    # floor so a destroyed (0-health) component still has some soak, not an instant pass-through
const DAMAGE_ABSORPTION_PER_DENSITY := 50.0 # dmg_absorbed per step = effective_density * DAMAGE_RAYMARCH_STEP * this
const LASER_HEAT_MODIFIER := 0.5       # fraction of absorbed laser damage converted to component heat
const KINETIC_HEAT_MODIFIER := 0.05    # fraction of absorbed non-laser damage converted to component heat -- lasers run 10x hotter per point of damage

const SHIP_COLLISION_RADIUS := 50.0    # physical hit/collision circle radius -- separate from the cross_section sensor stat

const RCS_SFX_TORQUE_THRESHOLD := 100.0 # torque above this plays the RCS thruster sound cue

const HIT_TRACE_DURATION := 3.0 # seconds a damage-raymarch trace lingers for the engineering panel's spatial view to fade out

var owner_id: int = -1

func _init() -> void:
	ship_components = ship_components.duplicate(true)
	iff_tags = iff_tags.duplicate(true)
	active_contacts = {}

var target_thrust: float = 0.0
var target_velocity: float = 0.0
var target_heading: float = 0.0
var steering_mode: int = 0 # 0 = Smooth, 1 = Combat
var linear_mode: int = 0 # 0 = Throttle, 1 = Velocity

var max_omega: float = 2.0
var max_speed: float = 1000.0
var iff_tags: Array = []

# M9b: declared spec-chart tier for ShipDesignValidator. Ships left at
# UNVALIDATED are skipped by the validator (opt-out, not a failure) -- see
# implementation_plans/m9b_spec_chart_design.md.
var ship_tier: int = ComponentSpec.Tier.UNVALIDATED

var actual_throttle: float = 0.0

var _cached_max_steps: int = 0
var _cached_aabb: Rect2 = Rect2()
var _aabb_cached: bool = false

func get_local_aabb() -> Rect2:
	if _aabb_cached:
		return _cached_aabb
	
	if ship_components.is_empty():
		_cached_aabb = Rect2(-10, -10, 20, 20)
	else:
		var min_x = INF; var max_x = -INF
		var min_y = INF; var max_y = -INF
		for c in ship_components:
			var r: Rect2 = c.get("rect", Rect2(-10, -10, 20, 20))
			min_x = min(min_x, r.position.x)
			max_x = max(max_x, r.position.x + r.size.x)
			min_y = min(min_y, r.position.y)
			max_y = max(max_y, r.position.y + r.size.y)
		_cached_aabb = Rect2(min_x, min_y, max_x - min_x, max_y - min_y)
	
	_aabb_cached = true
	return _cached_aabb

func get_bounding_radius() -> float:
	var aabb = get_local_aabb()
	var corners = [
		aabb.position,
		aabb.position + Vector2(aabb.size.x, 0),
		aabb.position + Vector2(0, aabb.size.y),
		aabb.position + aabb.size
	]
	var max_dist = 0.0
	for pt in corners:
		max_dist = max(max_dist, pt.length())
	return max_dist

# Loadout is empty on the generic Ship base. Each concrete ship class declares
# its own ship_components in _init() (see frigate.gd, sensor_drone.gd,
# missile.gd). M9a moved the frigate loadout that used to live here down into
# frigate.gd so a new ship class is a different component array, not a fork of
# this file.
var ship_components: Array = []

# Per-ship-class heat budget (overridden by Missile -- see missile.gd). These
# are vars, not consts, specifically so each ship class can have its own
# thermal envelope; the Frigate baseline values below were picked so a
# fully-loaded reactor (REACTOR_HEAT_COEFFICIENT * 1.0 power) plus full-burn
# engines roughly fills max_heat over several seconds of sustained combat,
# not so fast overheat punishes a single alpha strike, not so slow it's never
# a real constraint.
var current_heat: float = 10.0 # ambient starting heat, same order as REACTOR_HEAT_FLOOR
var max_heat: float = 200.0
var heat_dissipation_rate = 10.0
var current_heat_gen: float = 0.0

var is_dead: bool = false
var em_signature: float = 0.0

var transient_events: Array = []
var hit_traces: Array = []

func get_sys_health(sys_type: String) -> float:
	var h = 0.0
	for c in ship_components:
		if c["type"] == sys_type and c.get("powered_on", true):
			h += max(0.0, c["health"])
	return h

# Health-only check (ignores powered_on), used to gate ship death so switching
# a component off can never be mistaken for it being destroyed -- only an
# actual loss of health should be fatal.
func is_sys_destroyed(sys_type: String) -> bool:
	for c in ship_components:
		if c["type"] == sys_type and c["health"] > 0.0:
			return false
	return true

static func _iff_tags_overlap(tags_a: Array, tags_b: Array) -> bool:
	for tag in tags_a:
		if tags_b.has(tag):
			return true
	return false

static func classify_contact(signature: Dictionary, observer_iff_tags: Array) -> String:
	var is_friendly = _iff_tags_overlap(signature.get("iff_tags", []), observer_iff_tags)

	var cs = signature.get("cross_section", 0.0)
	var heat = signature.get("heat", 0.0)
	var em = signature.get("em_noise", 0.0)
	var density = signature.get("density", UNKNOWN_DENSITY_DEFAULT)

	# 1. Size check (Ordnance)
	if cs < ORDNANCE_CS_THRESHOLD and (em > ACTIVE_EM_THRESHOLD or heat > ORDNANCE_HEAT_THRESHOLD):
		if is_friendly:
			return "FRIENDLY ORDNANCE"
		else:
			return "INCOMING ORDNANCE"

	# 2. Emission check (Vessels)
	if cs >= ORDNANCE_CS_THRESHOLD and (em > ACTIVE_EM_THRESHOLD or heat > VESSEL_HEAT_THRESHOLD):
		if is_friendly:
			return "FRIENDLY VESSEL"
		else:
			return "UNIDENTIFIED VESSEL"

	# 3. Density check (Dead objects / Cold ships)
	if em <= ACTIVE_EM_THRESHOLD and heat <= VESSEL_HEAT_THRESHOLD:
		if density > ASTEROID_DENSITY_THRESHOLD and cs > ASTEROID_CS_THRESHOLD:
			return "ASTEROID"
		elif density <= ASTEROID_DENSITY_THRESHOLD:
			return "WRECKAGE"
			
	return "UNKNOWN ANOMALY"

func get_sys_max_health(sys_type: String) -> float:
	var h = 0.0
	for c in ship_components:
		if c["type"] == sys_type:
			h += c["max_health"]
	return h

func is_component_powered(comp_id: String) -> bool:
	for c in ship_components:
		if c["id"] == comp_id:
			if not (c.get("powered_on", true) and c["health"] > 0.0):
				return false
			# Reactor/hull don't draw power from a reactor themselves -- every
			# other type cascades off ship-wide reactor output, so killing or
			# switching off every reactor goes dark everywhere downstream,
			# and recovers automatically the instant a reactor comes back on.
			if c["type"] == "reactor" or c["type"] == "hull":
				return true
			return get_total_power_rating("reactor") > 0.0
	return false

func get_component_health_ratio(comp_id: String) -> float:
	for c in ship_components:
		if c["id"] == comp_id:
			return max(0.0, c["health"]) / max(1.0, c["max_health"])
	return 0.0

# Surviving fraction of TOTAL component health (1.0 pristine, 0.0 gutted). Used by the AI
# disengage trigger; also useful for UI / threat assessment.
func get_health_fraction() -> float:
	var current := 0.0
	var maximum := 0.0
	for c in ship_components:
		current += max(0.0, c["health"])
		maximum += c["max_health"]
	return current / maximum if maximum > 0.0 else 0.0

# Longest range of any currently-working comms component, or 0.0 if the ship
# has none/all are destroyed or powered off. A link between two ships is
# capped by the weaker of their two ranges -- see the datalink relay block.
func get_comms_range() -> float:
	var best_range = 0.0
	for c in get_components_by_type("comms"):
		if is_component_powered(c["id"]):
			best_range = max(best_range, c.get("range", 0.0))
	return best_range

func get_components_by_type(type: String) -> Array:
	return ship_components.filter(func(c): return c["type"] == type)

func get_component(comp_id: String) -> Dictionary:
	for c in ship_components:
		if c["id"] == comp_id:
			return c
	return {}

func get_component_origin(comp: Dictionary) -> Vector2:
	return comp["rect"].position

# M1b: mass and power rating are summed from components instead of being flat
# ship-level constants, so a "dual reactor"/"dual engine" ship degrades to
# whatever's still alive instead of needing special-casing.
func get_ship_mass() -> float:
	var total = 0.0
	for c in ship_components:
		var area = c["rect"].size.x * c["rect"].size.y
		total += area * c["density"] * MASS_SCALE
	return total

# Point-mass approximation: treats each component as a point mass at its rect
# centroid, ignores each box's own rotational inertia about its own center.
# Close enough for "roughly the right shape" -- not meant to be exact physics.
func get_ship_inertia() -> float:
	var total = 0.0
	for c in ship_components:
		var area = c["rect"].size.x * c["rect"].size.y
		var mass = area * c["density"] * MASS_SCALE
		var centroid = c["rect"].position + c["rect"].size / 2.0
		total += mass * centroid.length_squared()
	return total * INERTIA_SCALE

# Generic "sum a rating field across components of a type" helper -- powers
# get_total_power_rating, get_ship_max_thrust, get_ship_max_torque, etc.
# Weighted by health and gated by powered state, same as get_sys_health.
func get_total_rating(sys_type: String, field: String) -> float:
	var total = 0.0
	for c in ship_components:
		if c["type"] == sys_type and is_component_powered(c["id"]):
			total += c.get(field, 0.0) * get_component_health_ratio(c["id"])
	return total

func get_max_rating(sys_type: String, field: String) -> float:
	var total = 0.0
	for c in ship_components:
		if c["type"] == sys_type:
			total += c.get(field, 0.0)
	return total

func get_total_power_rating(sys_type: String) -> float:
	return get_total_rating(sys_type, "power_rating")

func get_max_power_rating(sys_type: String) -> float:
	return get_max_rating(sys_type, "power_rating")

# thrust_rating/torque_rating are authored per-engine-component fields, summed
# the same way power_rating is -- not derived from area/density, since that
# breaks ship-to-ship balance ratios that were deliberately tuned (see M1b
# appendix). A dual-engine ship's total degrades correctly if one dies.
func get_ship_max_thrust() -> float:
	return get_total_rating("engines", "thrust_rating")

func get_ship_max_torque() -> float:
	return get_total_rating("engines", "torque_rating")

# This engine's own share of the ship-wide throttle/torque heat -- apportioned
# by its share of total live thrust, with its own (not the fleet-wide) health
# ratio driving inefficiency. Reduces to "ship-wide heat, thrust_share = 1.0"
# for any ship with exactly one engine (every ship today).
func _engine_heat_contribution(comp: Dictionary, throttle: float, applied_torque: float, max_torque_now: float, ship_max_thrust: float) -> float:
	if not is_component_powered(comp["id"]) or ship_max_thrust <= 0.0:
		return 0.0
	var ratio = get_component_health_ratio(comp["id"])
	var inefficiency = max(1.0, 1.0 / max(0.1, ratio))
	var thrust_share = (comp.get("thrust_rating", 0.0) * ratio) / ship_max_thrust
	var h = abs(throttle) * 10.0 * inefficiency * thrust_share
	h += (abs(applied_torque) / max(1.0, max_torque_now)) * 5.0 * inefficiency * thrust_share
	return h

# Same fix as _engine_heat_contribution, for reactors: apportion the ship-wide
# slider-driven reactor heat by each reactor's share of total live power_rating
# instead of pooling the same value into every reactor component.
func _reactor_heat_contribution(comp: Dictionary, reactor_heat_total: float, ship_reactor_rating: float) -> float:
	if not is_component_powered(comp["id"]) or ship_reactor_rating <= 0.0:
		return 0.0
	var ratio = get_component_health_ratio(comp["id"])
	var reactor_share = (comp.get("power_rating", 0.0) * ratio) / ship_reactor_rating
	return reactor_heat_total * reactor_share

# Rectified, damage-scaled oscillation added on top of an engine's
# proportional-to-health EM baseline. Zero at full health; amplitude AND
# frequency both rise with damage (see ENGINE_OSC_* above). Phase is its own
# running accumulator (not wall-clock time) so the stutter restarts cleanly
# whenever a fresh injury starts it back up, instead of phase depending on
# how long the ship has existed.
func _engine_damage_oscillation(comp: Dictionary, health_ratio: float, delta: float) -> float:
	var damage_ratio = 1.0 - health_ratio
	if damage_ratio <= 0.0:
		comp["em_osc_phase"] = 0.0
		return 0.0
	var osc_freq = ENGINE_OSC_FREQ_BASE + damage_ratio * ENGINE_OSC_FREQ_RANGE
	var phase = comp.get("em_osc_phase", 0.0) + TAU * osc_freq * delta
	comp["em_osc_phase"] = phase
	return absf(sin(phase)) * damage_ratio * comp.get("power_rating", 0.0) * ENGINE_OSC_GAIN

# One-shot "reactor destroyed" EM whiteout: triggers once when health crosses
# from alive to dead, then decays over REACTOR_WHITEOUT_DURATION regardless of
# reactor size (a fixed decay-per-second constant would make bigger reactors'
# pulses linger longer for no reason).
func _update_reactor_whiteout(comp: Dictionary, delta: float) -> float:
	if comp.get("_prev_health", comp["health"]) > 0.0 and comp["health"] <= 0.0:
		var magnitude = comp.get("power_rating", 0.0) * REACTOR_WHITEOUT_MULTIPLIER
		comp["em_pulse"] = magnitude
		comp["_em_pulse_decay_rate"] = magnitude / REACTOR_WHITEOUT_DURATION
	comp["_prev_health"] = comp["health"]
	var pulse = max(0.0, comp.get("em_pulse", 0.0) - comp.get("_em_pulse_decay_rate", 0.0) * delta)
	comp["em_pulse"] = pulse
	return pulse

# Decays a component's combat-damage heat burst (from take_damage()) and
# returns the remaining amount so callers can add it on top of their own
# steady-state heat instead of it being clobbered outright.
func _decay_damage_heat(comp: Dictionary, delta: float) -> float:
	var damage_heat = max(0.0, comp.get("damage_heat", 0.0) - DAMAGE_HEAT_DECAY_RATE * delta)
	comp["damage_heat"] = damage_heat
	return damage_heat

# EM emission pattern is a function of component type, not an authored field:
# sensors and weapons already carry their own heading/arc_width (used for
# sensing/engagement arcs), so they emit directionally through that same
# cone for free. Everything else (reactor, engine, passive leakage) has no
# natural facing and stays omnidirectional.
func _is_directional_emitter(comp: Dictionary) -> bool:
	return comp["type"] == "sensors" or comp["type"] == "weapons"

# How much of one component's em_emission a receiver at angle_from_target
# (world-space angle from the receiver back to the emitting ship) actually
# sees, given the emitting ship's rotation. Omni sources use the existing
# rear-aspect dipole bias; directional sources (sensors/weapons) fall off
# across their own mount arc, same shape as the old sensor-only cone code.
func _received_em_power(comp: Dictionary, target_rotation: float, angle_from_target: float) -> float:
	var em_emission = comp.get("em_emission", 0.0)
	if em_emission <= 0.0:
		return 0.0
	if not _is_directional_emitter(comp):
		var relative_angle = angle_from_target - target_rotation
		var rear_bias = 1.0 + 0.5 * max(0.0, cos(relative_angle + PI))
		return em_emission * rear_bias
	var comp_heading = target_rotation + comp.get("heading", 0.0)
	var arc = comp.get("arc_width", TAU)
	var diff = abs(wrapf(angle_from_target - comp_heading, -PI, PI))
	if diff > arc / 2.0:
		return 0.0
	return em_emission * (1.0 - diff / (arc / 2.0))

# Sums received EM across every emitter a target's get_signature() exposes,
# replacing the old "one rear-biased scalar + sensor_config-only cone spikes"
# split with one consistent per-component pass.
func _total_received_em(sig: Dictionary, angle_from_target: float) -> float:
	var target_rotation = sig.get("rot", 0.0)
	var total = 0.0
	for comp in sig.get("em_emitters", []):
		total += _received_em_power(comp, target_rotation, angle_from_target)
	return total

# Fraction of rated power currently available for sys_type (0 if no such
# components exist). Reduces to is_component_powered(id) ? health_ratio : 0
# when there's exactly one component of that type, so it's a drop-in
# replacement for the old single-hardcoded-id checks.
func get_power_ratio(sys_type: String) -> float:
	var max_rating = get_max_power_rating(sys_type)
	if max_rating <= 0.0:
		return 0.0
	return get_total_power_rating(sys_type) / max_rating

# Legacy getters
var health: float:
	get: return get_sys_health("hull")
	set(value): pass # Obsolete, damage uses volumetric now

var base_heat: float:
	get: return current_heat

# Sensor Signature Profile
var signature_multiplier: float = 1.0

var cross_section: float:
	get:
		var aabb = get_local_aabb()
		return min(aabb.size.x, aabb.size.y) * signature_multiplier
var density: float = 90.0        # Solid armor

var sfx_engine: AudioStreamPlayer
var sfx_rcs: AudioStreamPlayer
var sfx_laser: AudioStreamPlayer
var sfx_missile: AudioStreamPlayer

# Set true to re-enable verbose combat traces ([Damage]/[PD]); off by default so normal
# play and headless tests are not flooded with per-hit / per-shot prints.
const COMBAT_DEBUG := false

func take_damage(amount: float, global_pos: Vector2 = Vector2.ZERO, global_dir: Vector2 = Vector2.ZERO, damage_type: String = "kinetic") -> void:
	if is_dead: return

	if COMBAT_DEBUG: print("[Damage] ", name, " taking ", amount, " ", damage_type, " damage at ", global_pos, " dir ", global_dir)

	# Player-feedback hook: surface "we got hit" to this ship's own terminal (impact
	# sound + controller punch + screen flash, scaled by amount). Cleared each frame
	# after the packet is built, same as the laser events. Other listeners guard on
	# type, so a "damage" event is ignored where it's not wanted.
	transient_events.append({"type": "damage", "amount": amount})

	if global_pos == Vector2.ZERO or global_dir == Vector2.ZERO:
		if COMBAT_DEBUG: print("[Damage] No position provided, applying fallback hull damage.")
		# Fallback: Just subtract health from first hull component
		for c in ship_components:
			if c["type"] == "hull":
				c["health"] -= amount
				break
	else:
		# Raymarch through components starting from local collision pos
		var local_pos = to_local(global_pos)
		var local_dir = global_dir.rotated(-rotation)
		
		var remaining_damage = amount
		var step_size = DAMAGE_RAYMARCH_STEP
		
		if _cached_max_steps == 0:
			var aabb = get_local_aabb()
			var max_dist = aabb.size.length()
			_cached_max_steps = int(ceil(max_dist / step_size))
			
		var tmin = -INF
		var tmax = INF
		var hit_box = true
		var aabb = get_local_aabb()
		for axis in [Vector2.AXIS_X, Vector2.AXIS_Y]:
			if abs(local_dir[axis]) < 0.0001:
				if local_pos[axis] < aabb.position[axis] or local_pos[axis] > aabb.position[axis] + aabb.size[axis]:
					hit_box = false
			else:
				var min_bound = aabb.position[axis]
				var max_bound = aabb.position[axis] + aabb.size[axis]
				var t1 = (min_bound - local_pos[axis]) / local_dir[axis]
				var t2 = (max_bound - local_pos[axis]) / local_dir[axis]
				if t1 > t2:
					var temp = t1
					t1 = t2
					t2 = temp
				tmin = max(tmin, t1)
				tmax = min(tmax, t2)
				
		if tmax >= tmin and tmax >= 0 and hit_box:
			local_pos = local_pos + local_dir * max(0.0, tmin)

		var max_steps = _cached_max_steps
		var current_pos = local_pos
		
		var trace = {
			"start_local": local_pos,
			"end_local": local_pos,
			"dir_local": local_dir,
			"segments": [],
			"time_remaining": HIT_TRACE_DURATION
		}
		
		var hit_something = false
		for i in range(max_steps):
			if remaining_damage <= 0: break
			
			var segment_hit = false
			
			for comp in ship_components:
				if comp["health"] <= 0: continue
				if comp["rect"].has_point(current_pos):
					hit_something = true
					segment_hit = true
					
					# Ablation: Effective density drops as component loses health
					var health_ratio = max(0.0, comp["health"] / comp.get("max_health", 1000.0))
					var effective_density = max(MIN_EFFECTIVE_DENSITY, comp["density"] * health_ratio)

					var dmg_absorbed = min(remaining_damage, effective_density * step_size * DAMAGE_ABSORPTION_PER_DENSITY)
					if dmg_absorbed > 0:
						comp["health"] -= dmg_absorbed

						# Laser hits add significantly more heat to the component
						var heat_modifier = LASER_HEAT_MODIFIER if damage_type == "laser" else KINETIC_HEAT_MODIFIER
						var heat_generated = dmg_absorbed * heat_modifier
						
						# Burst lives in its own field and decays over time (see
						# _decay_damage_heat) instead of comp["heat"], which the
						# per-frame dispatch loop below recomputes from scratch.
						comp["damage_heat"] = comp.get("damage_heat", 0.0) + heat_generated
						current_heat += heat_generated
						remaining_damage -= dmg_absorbed
			
			trace["segments"].append({
				"pos": current_pos,
				"dmg_remaining": remaining_damage,
				"hit": segment_hit
			})
			
			current_pos += local_dir * step_size
			trace["end_local"] = current_pos
			
		hit_traces.append(trace)

		if not hit_something:
			if COMBAT_DEBUG: print("[Damage] Raycast completely missed all internal components!")
			

	# Check death condition (reactor dead)
	if is_sys_destroyed("reactor") or is_sys_destroyed("hull"):
		print("[Damage] ", name, " suffers catastrophic failure and dies.")
		hulk()

func hulk() -> void:
	is_dead = true
	# Shut down all individual components
	for c in ship_components:
		c["powered_on"] = false
	target_thrust = 0.0
	actual_throttle = 0.0

func get_signature() -> Dictionary:
	return {
		"cross_section": cross_section,
		"heat": current_heat,
		"em_noise": em_signature,
		"density": density,
		"owner_id": owner_id,
		"iff_tags": iff_tags.duplicate(),
		"pos": position,
		"rot": rotation,
		"vel": linear_velocity,
		"sensors": active_sensor_sweeps,
		"sensor_config": get_components_by_type("sensors"),
		"em_emitters": get_components_by_type("reactor") + get_components_by_type("engines") + get_components_by_type("sensors") + get_components_by_type("weapons"),
		"contacts": active_contacts,
		"bounding_radius": get_bounding_radius(),
		"aabb": get_local_aabb()
	}

func _ready() -> void:
	if owner_id == -1:
		owner_id = int(name.replace("Ship_", ""))
		
	add_to_group("ships")

	mass = get_ship_mass()
	inertia = get_ship_inertia()
	gravity_scale = 0.0
	linear_damp_mode = RigidBody2D.DAMP_MODE_REPLACE
	linear_damp = 0.0 # No drag in space
	angular_damp_mode = RigidBody2D.DAMP_MODE_REPLACE
	angular_damp = 0.0 # No drag in space
	
	# Add collision shape so raycasts can hit the ship
	var collision = CollisionShape2D.new()
	var shape = CircleShape2D.new()
	shape.radius = get_bounding_radius()
	collision.shape = shape
	add_child(collision)
	
	sfx_engine = AudioStreamPlayer.new()
	var e_stream = load("res://assets/audio/engine.wav")
	if e_stream and e_stream is AudioStreamWAV: e_stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	sfx_engine.stream = e_stream
	add_child(sfx_engine)
	
	sfx_rcs = AudioStreamPlayer.new()
	var r_stream = load("res://assets/audio/rcs.wav")
	if r_stream and r_stream is AudioStreamWAV: r_stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	sfx_rcs.stream = r_stream
	add_child(sfx_rcs)
	
	sfx_laser = AudioStreamPlayer.new()
	sfx_laser.stream = load("res://assets/audio/laser.wav")
	add_child(sfx_laser)
	
	sfx_missile = AudioStreamPlayer.new()
	sfx_missile.stream = load("res://assets/audio/missile_launch.wav")
	add_child(sfx_missile)

var active_sensor_sweeps = {} # Map of id -> bins
var active_contacts = {}
var next_contact_id: int = 1

var _high_res_target_idx: int = 0
var _high_res_target_timer: float = 0.0

var manual_sensor_target: String = ""

@rpc("any_peer", "call_local")
func request_spawn(type: String) -> void:
	if not is_multiplayer_authority(): return
	var main = get_node_or_null("/root/Main")
	if not main: return
	
	if type == "asteroids":
		main._spawn_asteroids()
	elif type == "drone":
		main._spawn_drone()
	elif type == "friendly_drone":
		main._spawn_drone(true)
	elif type == "buoy":
		main._spawn_buoy()

# M10 sandbox: spawn a catalog hull (by display name) on a sandbox team
# (Friendly/Enemy/Pirate). The terminal's combined spawn control sends this;
# the host resolves the name to a ship script via ShipCatalog and routes it
# through main._spawn_ship().
@rpc("any_peer", "call_local")
func request_spawn_ship(ship_name: String, team: int) -> void:
	if not is_multiplayer_authority(): return
	var main = get_node_or_null("/root/Main")
	if not main: return
	main._spawn_ship_by_name(ship_name, team)


@rpc("any_peer", "call_local")
func set_sensor_state(sensor_id: String, is_active: bool) -> void:
	if not is_multiplayer_authority():
		return
	if multiplayer.get_remote_sender_id() != owner_id and multiplayer.get_remote_sender_id() != 1:
		if multiplayer.get_remote_sender_id() != 0:
			pass
	for s in get_components_by_type("sensors"):
		if s["id"] == sensor_id:
			s["active"] = is_active
			break

@rpc("any_peer", "call_local")
func set_all_sensors_state(is_active: bool) -> void:
	if not is_multiplayer_authority():
		return
	if multiplayer.get_remote_sender_id() != owner_id and multiplayer.get_remote_sender_id() != 1:
		if multiplayer.get_remote_sender_id() != 0:
			pass
	for s in get_components_by_type("sensors"):
		s["active"] = is_active

@rpc("any_peer", "call_local")
func set_sensor_target(target_id: String) -> void:
	if not is_multiplayer_authority(): return
	if multiplayer.get_remote_sender_id() != owner_id and multiplayer.get_remote_sender_id() != 1:
		if multiplayer.get_remote_sender_id() != 0: pass
	manual_sensor_target = target_id

func _physics_process(delta: float) -> void:
	if is_multiplayer_authority():
		for w in get_components_by_type("weapons"):
			if w["cooldown"] > 0:
				var cooldown_rate = 1.0
				var ratio = get_component_health_ratio(w["id"])
				if ratio > 0.0:
					cooldown_rate = ratio
				w["cooldown"] -= delta * cooldown_rate
				
		if not is_dead:
			_process_point_defense()
		
	var forward = Vector2.RIGHT.rotated(rotation)
	var current_forward_speed = linear_velocity.dot(forward)
	
	var active_max_thrust = get_ship_max_thrust()

	if linear_mode == 0:
		# Direct Throttle Control
		actual_throttle = target_thrust
	else:
		# Velocity Control (PID/Bang-Bang)
		var v_error = target_velocity - current_forward_speed
		var required_accel = v_error * VELOCITY_CONTROL_GAIN
		var required_force = required_accel * mass
		if active_max_thrust > 0.0:
			actual_throttle = required_force / active_max_thrust
		else:
			actual_throttle = 0.0
		
	# Apply limits based on steering mode
	if steering_mode == 0:
		actual_throttle = clampf(actual_throttle, -SMOOTH_MODE_THRUST_RATIO, SMOOTH_MODE_THRUST_RATIO)
	else:
		actual_throttle = clampf(actual_throttle, -1.0, 1.0)
	
	var is_my_ship = (multiplayer.get_unique_id() == owner_id)
	
	if active_max_thrust > 0.0 and actual_throttle != 0.0:
		apply_central_force(forward * actual_throttle * active_max_thrust)
		if is_my_ship and not sfx_engine.playing:
			sfx_engine.play()
	else:
		if sfx_engine.playing:
			sfx_engine.stop()
		
	# Enforce absolute speed limit (Reactor Safety Governor)
	if linear_velocity.length() > max_speed:
		linear_velocity = linear_velocity.normalized() * max_speed
	
	# Enforce absolute speed limit (Reactor Safety Governor)
	if linear_velocity.length() > max_speed:
		linear_velocity = linear_velocity.normalized() * max_speed
	
	# Time-Optimal Rotational Controller (Square-root curve braking)
	var angle_diff = wrapf(target_heading - rotation, -PI, PI)
	
	var ship_max_torque = get_ship_max_torque()

	var torque = 0.0
	var active_max_torque = 0.0
	if ship_max_torque > 0.0:
		active_max_torque = ship_max_torque if steering_mode == 1 else ship_max_torque * SMOOTH_MODE_TORQUE_RATIO
		var active_max_omega = (max_omega if steering_mode == 1 else max_omega * SMOOTH_MODE_OMEGA_RATIO) * get_power_ratio("engines")
		
		var alpha_max = active_max_torque / inertia
		
		var target_omega = sign(angle_diff) * sqrt(2.0 * alpha_max * abs(angle_diff))
		target_omega = clampf(target_omega, -active_max_omega, active_max_omega)
		
		var omega_error = target_omega - angular_velocity
		var required_alpha = omega_error * ROTATION_TRACKING_GAIN
		
		torque = required_alpha * inertia
		torque = clampf(torque, -active_max_torque, active_max_torque)
		
		apply_torque(torque)
	
	if abs(torque) > RCS_SFX_TORQUE_THRESHOLD:
		if is_my_ship and not sfx_rcs.playing:
			sfx_rcs.play()
	else:
		if sfx_rcs.playing:
			sfx_rcs.stop()
	
	# Pin dir_high_res scanner to forward
	for s in get_components_by_type("sensors"):
		if s["id"] == "dir_high_res":
			s["heading"] = rotation
	
	# Decay and dead-reckon contacts
	var to_remove = []
	for c_id in active_contacts:
		var c = active_contacts[c_id]
		c["last_seen_timer"] = c.get("last_seen_timer", 0.0) + delta
		c["pos_timer"] = c.get("pos_timer", 0.0) + delta
		
		# Dead-reckon their position based on velocity
		if c.has("vel") and typeof(c["vel"]) == TYPE_VECTOR2:
			c["pos"] += c["vel"] * delta
			
		if c["last_seen_timer"] > CONTACT_TIMEOUT:
			to_remove.append(c_id)
	for c_id in to_remove:
		active_contacts.erase(c_id)
	
	var bins_this_frame = []

	# --- Heat & Engineering Logic ---
	if is_multiplayer_authority():
		var heat_gen = 0.0
		var reactor_heat = REACTOR_HEAT_COEFFICIENT
		var ship_reactor_rating = get_total_power_rating("reactor")
		var ship_max_thrust = get_ship_max_thrust()

		var total_reactor_heat = 0.0
		for rct in get_components_by_type("reactor"):
			total_reactor_heat += _reactor_heat_contribution(rct, reactor_heat, ship_reactor_rating)

		var total_engine_heat = 0.0
		for eng in get_components_by_type("engines"):
			total_engine_heat += _engine_heat_contribution(eng, actual_throttle, torque, active_max_torque, ship_max_thrust)

		var passive_heat = 0.0
		var passive_em = 0.0
		for comp in ship_components:
			if comp["type"] != "hull" and is_component_powered(comp["id"]):
				passive_heat += PASSIVE_COMPONENT_HEAT
				passive_em += PASSIVE_COMPONENT_EM

		heat_gen = total_reactor_heat + total_engine_heat + passive_heat
		current_heat_gen = heat_gen
		
		current_heat += heat_gen * delta
		# Reactor-pumped active cooling needs reactor power; passive radiative
		# loss doesn't, so a powerless hulk still cools down over a couple of
		# minutes instead of freezing forever at its death-instant heat.
		var active_dissipation = max(PASSIVE_HEAT_DISSIPATION_RATE, heat_dissipation_rate * get_power_ratio("reactor"))
		current_heat -= active_dissipation * delta
		current_heat = clampf(current_heat, 0.0, max_heat)
		
		if current_heat >= max_heat:
			for c in ship_components:
				if c["type"] == "reactor":
					c["health"] -= OVERHEAT_DAMAGE_RATE * delta

		# Update Component EM & Heat
		var base_em = get_total_power_rating("reactor")
		var current_em = base_em + (abs(actual_throttle) * get_total_power_rating("engines"))
		var sensor_em = 0.0
		var sensor_power_ratio = get_sys_health("sensors") / max(1.0, get_sys_max_health("sensors"))
		if sensor_power_ratio > 0.0:
			for s in get_components_by_type("sensors"):
				if s.get("active", true):
					sensor_em += s.get("base_em_emission", 0.0) * sensor_power_ratio
		
		for comp in ship_components:
			var is_powered = is_component_powered(comp["id"])
			var b_heat = PASSIVE_COMPONENT_HEAT if (is_powered and comp["type"] != "hull") else 0.0
			var b_em = PASSIVE_COMPONENT_EM if (is_powered and comp["type"] != "hull") else 0.0

			if comp["type"] == "reactor":
				comp["heat"] = (REACTOR_HEAT_FLOOR + _reactor_heat_contribution(comp, reactor_heat, ship_reactor_rating) if is_powered else 0.0) + _decay_damage_heat(comp, delta)
				comp["em_emission"] = (comp.get("power_rating", 0.0) * get_component_health_ratio(comp["id"]) if is_powered else 0.0) + _update_reactor_whiteout(comp, delta)
			elif comp["type"] == "engines":
				comp["heat"] = b_heat + _engine_heat_contribution(comp, actual_throttle, torque, active_max_torque, ship_max_thrust) + _decay_damage_heat(comp, delta)
				var engine_health_ratio = get_component_health_ratio(comp["id"])
				comp["em_emission"] = b_em + abs(actual_throttle) * comp.get("power_rating", 0.0) * engine_health_ratio + _engine_damage_oscillation(comp, engine_health_ratio, delta)
			elif comp["type"] == "sensors":
				comp["heat"] = b_heat + (SENSOR_HEAT_FLOOR if is_powered else 0.0) + _decay_damage_heat(comp, delta)
				comp["em_emission"] = b_em + (comp.get("base_em_emission", 0.0) * sensor_power_ratio if is_powered else 0.0)
			elif comp["type"] == "weapons":
				comp["heat"] = b_heat + _decay_damage_heat(comp, delta)
				WeaponBehaviorRegistry.get_behavior(comp["weapon_type"]).tick(self, comp, delta)
				comp["em_emission"] += b_em
			else:
				# Hull and other non-generating types have no steady-state heat
				# of their own, but still carry combat-damage burst + decay.
				comp["heat"] = _decay_damage_heat(comp, delta)
				comp["em_emission"] = 0.0

		# Computed after the loop above so weapon fire pulses (just updated by
		# WeaponBehavior.tick()) are reflected the same frame instead of lagging
		# by one tick.
		var weapon_em = 0.0
		for w in get_components_by_type("weapons"):
			weapon_em += w.get("em_emission", 0.0)
		em_signature = current_em + sensor_em + passive_em + weapon_em

	# Sensor Sweeps
	var active_sensor_efficiency = get_sys_health("sensors") / max(1.0, get_sys_max_health("sensors"))
	
	for sensor in get_components_by_type("sensors"):
		if not is_component_powered(sensor["id"]):
			active_sensor_sweeps[sensor["id"]] = []
			continue

		var sensor_health_ratio = get_component_health_ratio(sensor["id"])
		if sensor_health_ratio <= 0.0 or active_sensor_efficiency <= 0.1:
			continue

		if not sensor.get("active", true):
			active_sensor_sweeps[sensor["id"]] = []
			continue

		sensor["timer"] -= delta
		if sensor["timer"] <= 0.0:
			sensor["timer"] = sensor["refresh_interval"]
			var active_range = sensor["range"] * sensor_health_ratio
			var bins = _run_sensor_sweep(sensor, active_range)
			active_sensor_sweeps[sensor["id"]] = bins
			bins_this_frame.append_array(bins)
	# Sort bins by accuracy (lowest bin_angle first). If multiple sensors sweep the
	# same target on the exact same frame, processing the most accurate one first
	# prevents lower-resolution sweeps from dragging the position backwards.
	bins_this_frame.sort_custom(func(a, b): return a.get("bin_angle", TAU) < b.get("bin_angle", TAU))
	
	# Correlate tracks
	for bin in bins_this_frame:
		var closest_contact_id = ""
		var bin_pos = bin.get("pos", Vector2.ZERO)
		var bin_instance_id = bin.get("instance_id", -1)
		var new_id = ""
		
		if bin_instance_id != -1:
			new_id = "TRK-%03d" % (abs(bin_instance_id) % 1000)
			bin["contact_id"] = new_id
			if active_contacts.has(new_id):
				closest_contact_id = new_id
		else:
			var closest_dist = CONTACT_CORRELATION_RANGE
			for c_id in active_contacts:
				var c = active_contacts[c_id]
				var dist = c["pos"].distance_to(bin_pos)
				if dist < closest_dist:
					closest_dist = dist
					closest_contact_id = c_id
				
		if closest_contact_id != "":
			var c = active_contacts[closest_contact_id]
			var bin_angle = bin.get("bin_angle", TAU)
			var current_res = c.get("resolution", TAU)
			var time_since_pos = c.get("pos_timer", 0.0)
			if bin_angle <= current_res or time_since_pos > CONTACT_RESOLUTION_STALE_TIME:
				if bin_angle < current_res:
					c["pos"] = bin_pos
					c["vel"] = bin.get("vel", Vector2.ZERO)
				else:
					c["pos"] = c["pos"].lerp(bin_pos, CONTACT_FUSION_SMOOTHING)
					c["vel"] = c["vel"].lerp(bin.get("vel", Vector2.ZERO), CONTACT_FUSION_SMOOTHING)
				
				c["resolution"] = bin_angle
				c["pos_timer"] = 0.0

				if bin.has("cross_section"): c["signature"]["cross_section"] = lerp(c["signature"].get("cross_section", 0.0), bin.get("cross_section", 0.0), CONTACT_FUSION_SMOOTHING)
				if bin.has("heat"): c["signature"]["heat"] = lerp(c["signature"].get("heat", 0.0), bin.get("heat", 0.0), CONTACT_FUSION_SMOOTHING)
				if bin.has("em_noise"): c["signature"]["em_noise"] = lerp(c["signature"].get("em_noise", 0.0), bin.get("em_noise", 0.0), CONTACT_FUSION_SMOOTHING)
				if bin.has("owner_id"): c["signature"]["owner_id"] = bin["owner_id"]
				if bin.has("iff_tags"): c["signature"]["iff_tags"] = bin["iff_tags"]
				if bin.has("instance_id"): c["instance_id"] = bin["instance_id"]
				
				c["classification"] = Ship.classify_contact(c["signature"], self.iff_tags)
						
			c["last_seen_timer"] = 0.0
		else:
			# New contact
			new_id = bin.get("contact_id", "")
			if new_id == "":
				new_id = "TRK-%03d" % next_contact_id
				next_contact_id += 1
			
			var classification = Ship.classify_contact(bin, self.iff_tags)
				
			active_contacts[new_id] = {
				"id": new_id,
				"instance_id": bin.get("instance_id", -1),
				"pos": bin_pos,
				"vel": bin.get("vel", Vector2.ZERO),
				"resolution": bin.get("bin_angle", TAU),
				"pos_timer": 0.0,
				"signature": {
					"cross_section": bin.get("cross_section", 0.0),
					"heat": bin.get("heat", 0.0),
					"em_noise": bin.get("em_noise", 0.0),
					"density": bin.get("density", 0.0),
					"owner_id": owner_id
				},
				"last_seen_timer": 0.0,
				"classification": classification
			}
			
	# Datalink Relay: friendly ships in mutual comms range and line-of-sight
	# share active_contacts via freshest-wins. This reruns from scratch every
	# tick (no persistent link graph), so multi-hop propagation falls out for
	# free -- a contact relayed into this ship's active_contacts this frame
	# is available to relay onward to a third ship next frame, one tick of
	# latency per hop instead of needing an explicitly modeled delay.
	var self_comms_range = get_comms_range()
	if self_comms_range > 0.0:
		var space_state = get_world_2d().direct_space_state
		for s in get_tree().get_nodes_in_group("ships"):
			if s == self or s.is_dead: continue
			if not _iff_tags_overlap(iff_tags, s.iff_tags): continue

			var their_comms_range = s.get_comms_range()
			if their_comms_range <= 0.0: continue

			var link_range = min(self_comms_range, their_comms_range)
			if position.distance_to(s.position) > link_range: continue

			var ray_query = PhysicsRayQueryParameters2D.create(position, s.position)
			ray_query.exclude = [self]
			var ray_res = space_state.intersect_ray(ray_query)
			if ray_res and ray_res.collider != s:
				continue # Line of sight blocked

			# A ship never appears in its own active_contacts (you don't sense
			# yourself), so without this, two linked friendlies would only
			# ever learn about third parties via relay, never get a clean
			# read on each other through the link itself. Synthesize a
			# ground-truth self-report -- zero staleness since it's live
			# telemetry, not a sensor return -- keyed by the same
			# instance_id-derived TRK id sensors would assign s, so it
			# correlates with (rather than duplicates) any independent
			# sensor detection of s.
			var self_report_id = "TRK-%03d" % (abs(s.get_instance_id()) % 1000)
			var relayed_contacts = s.active_contacts.duplicate()
			relayed_contacts[self_report_id] = {
				"id": self_report_id,
				"instance_id": s.get_instance_id(),
				"pos": s.position,
				"vel": s.linear_velocity,
				"resolution": 0.0,
				"pos_timer": 0.0,
				"signature": s.get_signature(),
				"last_seen_timer": 0.0,
				"classification": Ship.classify_contact(s.get_signature(), iff_tags)
			}

			for c_id in relayed_contacts:
				var external_contact = relayed_contacts[c_id]
				if not active_contacts.has(c_id):
					active_contacts[c_id] = external_contact.duplicate(true)
				else:
					var c = active_contacts[c_id]
					if external_contact["last_seen_timer"] < c["last_seen_timer"]:
						c["pos"] = external_contact["pos"]
						c["vel"] = external_contact["vel"]
						c["last_seen_timer"] = external_contact["last_seen_timer"]
						c["resolution"] = min(c["resolution"], external_contact["resolution"])

	if is_multiplayer_authority():
		var i = hit_traces.size() - 1
		while i >= 0:
			hit_traces[i]["time_remaining"] -= delta
			if hit_traces[i]["time_remaining"] <= 0.0:
				hit_traces.remove_at(i)
			i -= 1

func _run_sensor_sweep(sensor: Dictionary, active_range: float = 0.0) -> Array:
	var use_range = active_range if active_range > 0.0 else sensor["range"]
	var origin = position + get_component_origin(sensor).rotated(rotation)
	var space_state = get_world_2d().direct_space_state
	var query = PhysicsShapeQueryParameters2D.new()
	var shape = CircleShape2D.new()
	shape.radius = use_range
	query.shape = shape
	query.transform = Transform2D(0, origin)

	var results = space_state.intersect_shape(query, 128)
	
	var NUM_BINS = sensor["num_bins"]
	var ARC_WIDTH = sensor["arc_width"]
	var SENSOR_HEADING = rotation + sensor["heading"]
	var BIN_ANGLE = ARC_WIDTH / float(NUM_BINS)
	
	var bins = {}
	
	for hit in results:
		var collider = hit.collider
		if collider == self:
			continue
		
		if collider.has_method("get_signature"):
			var sig = collider.get_signature()
			
			var dist = origin.distance_to(collider.position)

			var ray_query = PhysicsRayQueryParameters2D.create(origin, collider.position)
			ray_query.exclude = [self]
			var ray_res = space_state.intersect_ray(ray_query)
			if ray_res and ray_res.collider != collider:
				continue # Blocked by obstacle

			# Heat (sig["heat"]) intentionally has NO distance/direction falloff
			# model, unlike EM above -- an active sensor that detects the target
			# at all (range/arc/LOS) reports its true current_heat unmodified.
			# This is a deliberate scope cut for now, not an oversight: give heat
			# the same observation-fidelity treatment as EM later if it's wanted.
			if sensor.get("sensor_type", "active") == "passive_em":
				# Sums every emitter's own contribution (omni rear-bias or
				# directional cone falloff per _received_em_power) instead of
				# one rear-biased scalar plus a sensor-only cone bolt-on.
				var angle_from_target = (origin - collider.position).angle()
				var em_power = _total_received_em(sig, angle_from_target)

				var received_em = em_power * (EM_FALLOFF_REFERENCE_DISTANCE / max(EM_FALLOFF_REFERENCE_DISTANCE, dist))
				if received_em < PASSIVE_EM_NOISE_FLOOR:
					continue # Passive EM only detects targets above noise floor (after falloff)

				# Report what was actually received (direction + distance
				# falloff applied), not the raw broadcast value -- otherwise
				# the directional model only ever gated detection, never what
				# gets classified/displayed once detected.
				sig["em_noise"] = received_em

			var angle = (collider.position - origin).angle()

			var rel_angle = wrapf(angle - SENSOR_HEADING, -PI, PI)
			var half_arc = ARC_WIDTH / 2.0

			if rel_angle >= -half_arc and rel_angle <= half_arc:
				var cone_local_angle = rel_angle + half_arc
				var bin_idx = int(cone_local_angle / BIN_ANGLE)
				if bin_idx >= NUM_BINS: bin_idx = NUM_BINS - 1
				if bin_idx < 0: bin_idx = 0

				if not bins.has(bin_idx):
					bins[bin_idx] = []

				sig["_raw_pos"] = collider.position
				sig["_raw_dist"] = dist
				sig["instance_id"] = collider.get_instance_id()
				if sensor.get("sensor_type", "active") == "passive_em":
					sig.erase("cross_section")
					sig.erase("heat") # passive EM doesn't sense heat at all, by design
					sig.erase("density")
					# sig["em_noise"] is already the received (direction +
					# distance falloff applied) value set above.
					
				bins[bin_idx].append(sig)
	
	var sweep_output = []
	
	# Aggregate bins
	for bin_idx in bins.keys():
		var objects = bins[bin_idx]
		var merged = {
			"count": objects.size()
		}
		
		var total_cs = 0.0
		var max_heat = -1.0
		var max_em = -1.0
		var weighted_dist = 0.0
		var weighted_vel = Vector2.ZERO
		var bin_owner = -1
		var max_cs = -1.0
		var primary_instance_id = -1
		
		for obj in objects:
			var cs = obj.get("cross_section", 0.0)
			
			if obj.has("heat"):
				max_heat = max(max_heat, obj.get("heat", 0.0))
			if obj.has("em_noise"):
				max_em = max(max_em, obj.get("em_noise", 0.0))
				
			if obj.has("owner_id"):
				bin_owner = obj["owner_id"]
			if obj.has("iff_tags") and not merged.has("iff_tags"):
				merged["iff_tags"] = obj["iff_tags"].duplicate()
				
			if cs > max_cs:
				max_cs = cs
				primary_instance_id = obj.get("instance_id", -1)
			
			total_cs += cs
			weighted_dist += obj["_raw_dist"] * max(cs, 1.0)
			weighted_vel += obj.get("vel", Vector2.ZERO) * max(cs, 1.0)
		
		if total_cs > 0:
			weighted_dist /= total_cs
			weighted_vel /= total_cs
			var total_density = 0.0
			for obj in objects:
				total_density += obj.get("density", 0.0) * obj.get("cross_section", 1.0)
			merged["density"] = total_density / total_cs
		else:
			weighted_dist = objects[0]["_raw_dist"]
			if objects[0].has("density"):
				merged["density"] = objects[0].get("density", 0.0)
				
		if total_cs > 0.0:
			merged["cross_section"] = total_cs
		if max_heat >= 0.0:
			merged["heat"] = max_heat
		if max_em >= 0.0:
			merged["em_noise"] = max_em
			
		var bin_center_angle = SENSOR_HEADING - (ARC_WIDTH / 2.0) + (bin_idx * BIN_ANGLE) + (BIN_ANGLE / 2.0)
		merged["distance"] = weighted_dist
		var noisy_dist = weighted_dist * (1.0 + randf_range(-SENSOR_POS_NOISE, SENSOR_POS_NOISE))
		var noisy_angle = bin_center_angle + randf_range(-BIN_ANGLE * SENSOR_POS_NOISE * 50.0, BIN_ANGLE * SENSOR_POS_NOISE * 50.0) # slightly larger spread within the bin
		merged["pos"] = origin + Vector2(noisy_dist, 0).rotated(noisy_angle)
		
		# Cheat velocity with noise
		var noisy_vel = weighted_vel * (1.0 + randf_range(-SENSOR_VELOCITY_NOISE, SENSOR_VELOCITY_NOISE))
		noisy_vel = noisy_vel.rotated(randf_range(-SENSOR_VELOCITY_NOISE, SENSOR_VELOCITY_NOISE))
		merged["vel"] = noisy_vel
		
		merged["bin_idx"] = bin_idx
		merged["bin_angle"] = BIN_ANGLE
		merged["sensor_heading"] = SENSOR_HEADING
		merged["sensor_arc_width"] = ARC_WIDTH
		merged["sensor_range"] = sensor["range"]
		merged["sensor_id"] = sensor["id"]
		merged["owner_id"] = bin_owner
		merged["instance_id"] = primary_instance_id
		
		sweep_output.append(merged)
		
	return sweep_output

@rpc("any_peer", "call_local")
func set_component_power(component_id: String, active: bool) -> void:
	if not is_multiplayer_authority() or is_dead:
		return
	if multiplayer.get_remote_sender_id() != owner_id and multiplayer.get_remote_sender_id() != 1:
		if multiplayer.get_remote_sender_id() != 0:
			return
	for c in ship_components:
		if c["id"] == component_id and c.get("switchable", false):
			c["powered_on"] = active
			break

@rpc("any_peer", "call_local")
func fire_weapon(weapon_id: String, target_pos: Vector2, target_contact_id: String) -> void:
	if not is_multiplayer_authority() or is_dead:
		return # Only host executes this
		
	# Verify client owns this ship
	if multiplayer.get_remote_sender_id() != owner_id and multiplayer.get_remote_sender_id() != 1:
		if multiplayer.get_remote_sender_id() != 0:
			pass
			
	var weapon_data = get_component(weapon_id)
	if weapon_data.is_empty():
		print("fire_weapon failed: unknown weapon ", weapon_id)
		return

	var behavior = WeaponBehaviorRegistry.get_behavior(weapon_data["weapon_type"])
	if not behavior.can_fire(self, weapon_data, target_contact_id):
		# Expected control flow: the AI's fire_opportunity sprays the whole loadout each
		# tick and lets can_fire gate each one, so most calls "fail" on arc/cooldown. Not
		# an error -- stay silent (was a debug print that flooded headless logs).
		return

	behavior.execute_fire(self, weapon_data, target_pos, target_contact_id)

# ----------------------------------------------------
# M12a: Weapon groups & massed fire
# ----------------------------------------------------
# A "group" lets the player and the AI reason about a battery as a unit (a broadside)
# instead of N individual hardpoints, and is the handle for massed fire. Each weapon
# component MAY declare an explicit "group"; absent that it is derived from the mount
# bearing, so existing ship loadouts need no edits. Forward is +X, +Y is starboard
# (right), so heading -PI/2 is a port mount and +PI/2 is starboard (see frigate.gd).
const WEAPON_GROUP_FWD := "fwd"
const WEAPON_GROUP_AFT := "aft"
const WEAPON_GROUP_PORT := "port"
const WEAPON_GROUP_STBD := "stbd"

func get_weapon_group_id(comp: Dictionary) -> String:
	if comp.has("group"):
		return comp["group"]
	var h = wrapf(comp.get("heading", 0.0), -PI, PI)
	if abs(h) < PI / 6.0:
		return WEAPON_GROUP_FWD
	if abs(abs(h) - PI) < PI / 6.0:
		return WEAPON_GROUP_AFT
	return WEAPON_GROUP_PORT if h < 0.0 else WEAPON_GROUP_STBD

# { group_id: [weapon_id, ...] } over all weapon components.
func get_weapon_groups() -> Dictionary:
	var groups := {}
	for w in get_components_by_type("weapons"):
		var gid = get_weapon_group_id(w)
		if not groups.has(gid):
			groups[gid] = []
		groups[gid].append(w["id"])
	return groups

# Fire EVERY weapon in a group that currently can fire, in this single call (one physics
# tick). That single-tick simultaneity is what saturates point defense -- the heavy-ship
# massed-fire advantage a trickle of one missile can never achieve. Returns the count
# actually fired.
func fire_group(group_id: String, target_pos: Vector2, target_contact_id: String) -> int:
	if not is_multiplayer_authority() or is_dead:
		return 0
	var fired := 0
	for w in get_components_by_type("weapons"):
		if get_weapon_group_id(w) != group_id:
			continue
		var behavior = WeaponBehaviorRegistry.get_behavior(w["weapon_type"])
		if behavior.can_fire(self, w, target_contact_id):
			behavior.execute_fire(self, w, target_pos, target_contact_id)
			fired += 1
	return fired

# Readiness snapshot for a group without firing -- for the weapons-panel group button
# and AI utility scoring. `ready` counts weapons whose can_fire() passes right now
# (ammo + cooldown + power + arc), `total` is the group's size.
func get_group_status(group_id: String, target_contact_id: String) -> Dictionary:
	var total := 0
	var ready := 0
	for w in get_components_by_type("weapons"):
		if get_weapon_group_id(w) != group_id:
			continue
		total += 1
		var behavior = WeaponBehaviorRegistry.get_behavior(w["weapon_type"])
		if behavior.can_fire(self, w, target_contact_id):
			ready += 1
	return {"ready": ready, "total": total}

# Massed-fire TIMING. Among a group's weapons of one type that could still contribute to
# a volley -- alive, powered, and with ammo remaining -- are they ALL off cooldown? If
# so the volley should loose now so every tube launches in the same tick and saturates
# point defense; if any such tube is still cooling we hold and wait for it. Tubes that
# are damaged, out of ammo, or disabled are EXCLUDED -- we never wait on a tube that will
# never come ready. Returns false when no tube is live (nothing to volley).
func is_group_volley_ready(group_id: String, weapon_type: String) -> bool:
	var live := 0
	var ready := 0
	for w in get_components_by_type("weapons"):
		if get_weapon_group_id(w) != group_id:
			continue
		if w["weapon_type"] != weapon_type:
			continue
		if w["health"] <= 0.0:                 # damaged -- never wait on it
			continue
		if w["ammo"] <= 0:                      # out of ammo -- never wait on it
			continue
		if not is_component_powered(w["id"]):   # disabled / unpowered -- never wait on it
			continue
		live += 1
		if w.get("cooldown", 0.0) <= 0.0:
			ready += 1
	return live > 0 and ready == live

func _process_point_defense() -> void:
	var main_node = get_tree().current_scene
	if not is_instance_valid(main_node): return

	var ready_lasers = []
	var max_ready_range = 0.0
	for w in get_components_by_type("weapons"):
		if w["weapon_type"] == "laser" and w["ammo"] > 0 and w["cooldown"] <= 0.0:
			if is_component_powered(w["id"]):
				ready_lasers.append(w["id"])
				max_ready_range = max(max_ready_range, w["range"])

	if ready_lasers.is_empty():
		return

	# Shortest-range first, so a target gets the smallest laser that can
	# actually reach it -- reserving longer-range lasers for farther targets
	# instead of spending them on whatever's first in the component list.
	ready_lasers.sort_custom(func(a, b): return get_component(a)["range"] < get_component(b)["range"])

	var behavior = WeaponBehaviorRegistry.get_behavior("laser")

	# Gather qualifying targets with enough info to prioritize them: least
	# shot-at first (we get little feedback on hits, so spread shots around),
	# then closest. Engagement range comes from each laser's own authored
	# range via can_fire() below, not a flat ship-wide number -- this filter
	# is just "could ANY ready laser conceivably reach this" to avoid sorting
	# targets nothing can touch.
	var targets = []
	for c_id in active_contacts:
		var contact = active_contacts[c_id]
		if contact.get("classification", "") != "INCOMING ORDNANCE":
			continue
		var body = instance_from_id(contact.get("instance_id", -1))
		if not is_instance_valid(body) or body == self: continue
		if body is Ship and body.is_dead: continue
		var dist = position.distance_to(body.position)
		if dist > max_ready_range: continue
		targets.append({"c_id": c_id, "body": body, "dist": dist, "shots_fired": contact.get("pd_shots_fired", 0)})

	targets.sort_custom(func(a, b):
		if a["shots_fired"] != b["shots_fired"]:
			return a["shots_fired"] < b["shots_fired"]
		return a["dist"] < b["dist"])

	# One pass only assigns each target its single highest-priority laser --
	# with fewer targets than ready lasers (the common single-missile case)
	# that left the rest idle instead of concentrating fire. Keep re-passing
	# the same priority-ordered target list until every ready laser has
	# fired or none of them can reach any remaining target.
	var fired_any = true
	while not ready_lasers.is_empty() and fired_any:
		fired_any = false
		for t in targets:
			if ready_lasers.is_empty(): break

			var c_id = t["c_id"]
			var body = t["body"]

			for w_id in ready_lasers:
				var weapon_data = get_component(w_id)

				if behavior.can_fire(self, weapon_data, c_id):
					var start_pos = position + get_component_origin(weapon_data).rotated(rotation)
					behavior.execute_fire(self, weapon_data, body.position, c_id)

					transient_events.append({
						"type": "laser",
						"start_pos": start_pos,
						"end_pos": body.position
					})

					t["shots_fired"] += 1
					active_contacts[c_id]["pd_shots_fired"] = t["shots_fired"]

					if COMBAT_DEBUG: print("[PD] ", name, " shooting at ", body.name, " (", c_id, ")")
					ready_lasers.erase(w_id)
					fired_any = true
					break



func apply_control_input(thrust: float, t_vel: float, heading: float, s_mode: int, l_mode: int) -> void:
	target_thrust = clampf(thrust, -1.0, 1.0)
	target_velocity = clampf(t_vel, -max_speed, max_speed)
	target_heading = heading
	steering_mode = s_mode
	linear_mode = l_mode



